### ISSUE TITLE
plan for trim, extend, offset

### ISSUE THREAD

**Issue by ekswathi** [hlorus/CAD_Sketcher#100]
Any plan for basic cad options like trim, extend, fillet and offset ?

**Comment by TheMakerTales** [comment]
Hi ekswathi,
Thanks for the message it's great to hear from the community.

I would recommend going through the roadmap that can be found here: [Road map](https://github.com/users/hlorus/projects/1/views/1) 
Soon this will be a lot more visible so thank you for your patients in that regard.
If you are looking to start a discussion the best place would be in the [discord](https://discord.gg/EyRjypztmf).

Lastly if you are sure the feature is not planned, already in CAD Sketcher or already requests the best please to post it up in on the Github discussions for[ feature requests ](https://github.com/hlorus/CAD_Sketcher/discussions/categories/feature-requests)
If you could also keep feature requests down to one feature at a time that would be great!

From my knowledge I'm pretty sure trimming is planned but maybe you should suggest "extending" and "offset's" be sure to explain them well and sell the point of how this would benefit the workflow as this will get more developers interested in helping out.
