### ISSUE TITLE
[REQUEST] "Angle" Proper Positioning

### ISSUE THREAD

**Issue by hbfortunato** [hlorus/CAD_Sketcher#102]
I have just tested the addons, and this was the first problem I have encountered. When creating an angle from two lines, the angle usually gets created in a weird position where it is usually positioned outside of the selected area not getting the exact angle from the position you want to.

![image](https://user-images.githubusercontent.com/104838593/166455493-b3d11336-fe12-4c2d-b4ae-772be411028c.png)

as you can see in the picture, the angle I created was always positioned outside even if I want it inside or in the blue that I have drawn. which should have been the most position because those were the ones with an actual lines

I think this one will be fix that allows the user to put an angle on the absolute position they want. like this
![image](https://user-images.githubusercontent.com/104838593/166456387-7430798f-f26f-41d8-a4b5-d076ab2e099c.png)

Thank you

**Comment by TheMakerTales** [comment]
Hi hbfortunato,
Thanks for the request but I'll find that this is already part of CAD Sketcher. Please be sure to check the setting of each dimensioning constraint in there left click menu
![Invert angel](https://user-images.githubusercontent.com/103122109/166675395-01439687-5b09-4275-997d-a73ebf88459a.gif)
.
