### ISSUE TITLE
Incorrect highlighting of constraints [BUG]

### ISSUE THREAD

**Issue by ZanQdo** [hlorus/CAD_Sketcher#103]
### Description

Mouse over highlighting seems to have problems in my system

Operating system: Windows-10-10.0.19044-SP0 64 Bits
Graphics card: NVIDIA GeForce GTX 1080 with Max-Q Design/PCIe/SSE2 NVIDIA Corporation 4.5.0 NVIDIA 512.59

Here is a video demonstration of the problem where highlighting is wrong (notice the position of the mouse cursor and which constraint gets highlighted)

https://user-images.githubusercontent.com/999476/166588333-9455a2fc-8932-428c-ae09-21a6854b89e2.mp4

### Addon Version

0.22.2

### Blender Version

3.3.0

### What platform are you running on?

Windows

### Test file

[Distance.zip](https://github.com/hlorus/CAD_Sketcher/files/8622313/Distance.zip)

**Comment by hlorus** [comment]
Thanks for reporting, could you share the blend file?

**Comment by ZanQdo** [comment]
Attached test file to the original post

**Comment by hlorus** [comment]
Alright, bisecting led to https://developer.blender.org/rB9dadd8bdb101fd5c06cd6ca7aa708a6ce6f13d47 as the first bad commit. Going through the tasks it looks like this has been reported as a high prio bug, see:
https://developer.blender.org/T97771

Let's hope this gets fixed :)

**Comment by ZanQdo** [comment]
Ah, no wonder, it seemed to have appeared in the latest versions indeed. That Campbell! :)

**Comment by hlorus** [comment]
This should be resolved as the causing commits have been reverted.
