### ISSUE TITLE
tried to remove the app save the pref, and then install. cannot clean the interface, the app became less stable than 0.22[BUG]

### ISSUE THREAD

**Issue by victorktliu** [hlorus/CAD_Sketcher#115]
### Contact Details

victorktliu@yahoo.com

### Description

A bug happened!

### Addon Version

latest

### Blender Version

3.1

### What platform are you running on?

Windows

**Comment by hlorus** [comment]
Hi there,
I would recommend heading over to the [discord](https://discord.gg/GzpJsShgxa) to post your problem either in the [ installation-help ] or [ help ] channel.
If you're sure that you've found a valid bug that hasn't been reported before please follow the [Report a Bug Guide](https://github.com/hlorus/CAD_Sketcher/discussions/107) and provide as much information as possible.
