### ISSUE TITLE
[BUG] Angle constraint causing jumping when inverting constraint

### ISSUE THREAD

**Issue by ZanQdo** [hlorus/CAD_Sketcher#126]
**Motivation / Existing Problem**
Let's say we are constraining the external angle to 45 degrees
![image](https://user-images.githubusercontent.com/999476/168005017-3b1700cd-b8df-4f1a-b77e-189b3292e63d.png)

When inverting the constraint to the inside. Those 45 degrees are no longer applicable
![image](https://user-images.githubusercontent.com/999476/168005212-ef3e88c7-50aa-4dbe-8e1f-1c0dea8b5b05.png)

Instead, 90 degrees should be added to get 135 degrees and retain the same angle
![image](https://user-images.githubusercontent.com/999476/168005766-1ed88421-98c2-4754-a8a5-cb68b62af3bd.png)

**Comment by exegetor** [comment]
I might have found the problem.  I think the Invert setting is checked too early and a new angle (135) is sent to the solver, which needs to find new geometry for the "new angle".   I would leave the solver data alone and have the Gizmo check the Invert setting and draw helper lines accordingly.  If that sound like a good plan, I can get that done tomorrow night.

**Comment by hlorus** [comment]
> I might have found the problem.  I think the Invert setting is checked too early and a new angle (135) is sent to the solver, which needs to find new geometry for the "new angle".   I would leave the solver data alone and have the Gizmo check the Invert setting and draw helper lines accordingly.  If that sound like a good plan, I can get that done tomorrow night.

Not exactly sure what the right approach would be here, just keep in mind that the solver method "addAngle" takes an invert option as input, therefore i guess it makes sense to pass the constraints invert setting to the solver.

It might make sense to modify the constraint value from the invert setting's update callback.

**Comment by exegetor** [comment]
I've been having a bit of "technical difficulties"... using Visual Studio Code, if I add anything to update_system_cb(), it  triggers
some kind of error when it hits the callback function... the "def" line.  Breakpoints stop working also.  Possibly somthing wrong in the IDE?

```
[class_defines.py, from line 1890]
def update_system_cb(self, context):
    if hasattr(self, "label"):
        if self.label == "Angle":
            self.value = math.pi - self.value
    sketch = context.scene.sketcher.active_sketch
    solve_system(context, sketch=sketch) 

```
The error message is useless, and occurs numerous time.  No traceback, just a reference to the function definition line:
```
Traceback (most recent call last):
File "C:\Users\shann\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\CAD_Sketcher-main\class_defines.py", line 1890, in update_system_cb
```

Is there something wrong with the python syntax?  (of course, the two if statements can go on one line, and who knows if the logic's good, but damn, I can't even debug it!

**Comment by exegetor** [comment]
I put up a PR before noticing the different behavior between the pop-up that appears when you initially set the constraint, vs the context menu Invert setting for an Angle already in place.  The 2nd works great, but the 1st  (seemingly) doesn't apply valve = pi - value, so the geometry jumps accordingly.  I did not forsee that!
