### ISSUE TITLE
Dynamically set the workplane based off existing geometry

### ISSUE THREAD

**Issue by theoryshaw** [hlorus/CAD_Sketcher#13]
**Motivation / Existing Problem**
Currently no way to create a non-orthogonal workplane

**Description**
Pick a rotated workplane based off existing geometry

**Alternative Solutions**
When creating a new sketch, or perhaps even when you edit an existing one, you can dynamically set the workplane based off existing geometry

![2022-02-13_12-32-18](https://user-images.githubusercontent.com/507113/153769430-0258a2e1-a9bd-4a71-9c11-050e5a1ffe36.gif)

**Comment by hlorus** [comment]
> Cool. using ![image](https://user-images.githubusercontent.com/507113/153770671-d10c1f34-c175-4c72-9d93-2bf36b966352.png) how do you rotate it to specific dimensions in space?  Can you rotate it after the fact, once it's placed?
> 

You can enter exact angles from the redo panel.

**Comment by theoryshaw** [comment]
Thanks @hlorus for sharing the following GIF.  I uploaded it here, for Passerbys...
![workplane_tool](https://user-images.githubusercontent.com/507113/153891725-0350a755-43dd-442c-a1e1-27fe45a7d243.gif)

**Comment by hlorus** [comment]
This functionality is already implemented. Having workplanes move with the mesh they're placed on is tracked in #10.
