### ISSUE TITLE
First time Running Failed BUG

### ISSUE THREAD

**Issue by Darrenww** [hlorus/CAD_Sketcher#133]
### Contact Details

stilwellwu@gmail.com

### Description

The installation seems sucessful ,but cant run on Blender 2.82

![image](https://user-images.githubusercontent.com/105860089/169288445-ea00ae2b-0ad2-489b-8e8e-e79c4a6aa72c.png)
![image](https://user-images.githubusercontent.com/105860089/169288580-aec66f9c-aceb-4b7a-8d47-082c389a4edb.png)

### Addon Version

0.22.6

### Blender Version

2.82

### What platform are you running on?

Windows

**Comment by hlorus** [comment]
The addon is supported for blender 2.92 and above, i assume that's the cause of your problem.
