### ISSUE TITLE
Typo in 2D line tool: "Continuose draw" should be "continuous draw"

### ISSUE THREAD

**Issue by Intuos5** [hlorus/CAD_Sketcher#139]
There's a typo in the 2D line tool:
![afbeelding](https://user-images.githubusercontent.com/63149655/170230861-fc4b6c3d-1d26-48f8-b680-d4390f879e12.png)
"Continuose draw" should be "continuous draw"

**Comment by hlorus** [comment]
Thanks for pointing out.
