### ISSUE TITLE
[REQUEST] Option to delete a sketch by right clicking on the Sketch name in the N-panel

### ISSUE THREAD

**Issue by Intuos5** [hlorus/CAD_Sketcher#144]
**Motivation / Existing Problem**
Currently, there seems to be no way to delete a sketch if it is not converted to a Mesh or Bezier Curve. 

**Description**
To solve this problem, I propose to add a right click option in the N-panel to remove a sketch. 

**Alternative Solutions**
Alternatively, hitting the delete button in the Sketches list should also delete a sketch. 

**Workaround**
Convert the sketch to a mesh or bezier curve, select the mesh or curve and delete it. This also deletes the sketch. But this cannot be used reliably on open sketches (e.g. two crossing lines that are fully constrained).

**Comment by hlorus** [comment]
You should be able to delete any active sketch, there's a button in th sidebar,right? It would be great though if a sketch could be deleted if it's not active but i'm afraid it's not possible to use right click on a sketch in the ui list.

**Comment by Intuos5** [comment]
Could there also be a button to delete any non-active sketches? So select a sketch and hit the button or use a hotkey?

**Comment by hlorus** [comment]
Not sure about using a hotkey but maybe just show a X for the active list element.

**Comment by Intuos5** [comment]
Just FYI I tend to hotkey everything if I can, an X is fine by me.
