### ISSUE TITLE
[BUG] Constraint text location doesn't follow font size

### ISSUE THREAD

**Issue by Intuos5** [hlorus/CAD_Sketcher#145]
**Motivation / Existing Problem**
Currently, the dimension text origin is on top of the dimension line (it used the midpoint). This makes it so that the text overlaps with the line.

**Description**
I propose to add a spacing in between the two. This spacing could be 1/4 of the Font size or 1/3 of the Font size (would have to experiment on that). That way, if I increase the text size, the spacing scales accordingly. 

**Mockup**
It would look close to this in terms of the result. By changing the spacing factor, it would be scaling the white space in a more appropriate manner. 
https://user-images.githubusercontent.com/63149655/170654664-8c66c1b5-8b99-4a2d-9658-d3be7c5ff08e.mp4

**Alternative Solutions**
Another visibility option is to draw a box under the text that would clip the line, but then it would also clip the grid and look weird.
Splitting the dimension line itself would make them hard to read as well.

**Comment by exegetor** [comment]
I think I have a good prototype for this, implemented for Distance only.  Comments and criticism welcome.
Sorry the video isn't great but I'm already asleep...
see PR 185



https://user-images.githubusercontent.com/10360161/173744307-86f05108-f37d-407c-af1c-9fdc05fc8357.mp4
