### ISSUE TITLE
Constraint Icons in N-Panel

### ISSUE THREAD

**Issue by hlorus** [hlorus/CAD_Sketcher#160]
### Discussed in https://github.com/hlorus/CAD_Sketcher/discussions/122

<div type='discussions-op-text'>

<sup>Originally posted by **coleorloff** May 10, 2022</sup>
**Motivation / Existing Problem**
It's a little difficult to "read" sketches without familiarity with the constraint icons. (It's also a Blender UI convention to have icons paired with menu items.)

**Description**
Add constraint icons next to their name in the CAD Sketcher N-panel. T

his would provide a positive feedback loop in terms of visually identifying symbols within the system and "reading" your sketches, both for beginners and more advanced users.

**Mock-Up**
Note: highlighted area shows a selection of constraints paired with their icons. The goal would be to have all constraints in the menu paired with their icon. This is only for illustrative purposes. 

![CADSketcher_N-panel_proposal](https://user-images.githubusercontent.com/8648879/167663531-5cf0eb98-793a-4ee2-812e-39c235e36e85.png)

</div>

Implantation :
- How custom icons can be added to the interface is documented [here](https://docs.blender.org/api/current/bpy.utils.previews.html#bpy.utils.previews.ImagePreviewCollection)
- It would be great to use the same icons in the 3d viewport to avoid confusion. Therefore it would be nice if icon_manager.py could read the icon data that is used for the interface.

**Comment by hlorus** [comment]
That would be great, lets try to have this for 1.0

**Comment by hlorus** [comment]
A few notes: The icons that are currently drawn are blender geometry icons, same as they are used in the toolbar. Theses types of icons cannot be drawn in the layout.
I suggest to look at the documentation [here](https://hlorus.github.io/CAD_Sketcher/)
There are some people in the discord that are willing to help out with icons, best to ask there for help.

**Comment by Mortal-Engine** [comment]
Hi! Whats the icon size that you need? 128x128 seems to be food for KDE desktop icons

**Comment by Mortal-Engine** [comment]
![image](https://user-images.githubusercontent.com/65218891/173741773-2b5bf0f2-73a1-45d5-a100-a37a2e99c1dd.png)

![image](https://user-images.githubusercontent.com/65218891/173741806-9186fce5-c54d-4fb6-9eef-93181c90e0eb.png)

Would these types of icons work? There are taken directly from FreeCAD and recolored to match the CAD Sketcher theme

**Comment by amrsoll** [comment]
I think it would be good to have a variety of colors to better distinguish them, or have them follow the sketcher theme colors (which can be modified by the user)

**Comment by hlorus** [comment]
IMO having different colors isn't a good idea as it kind of goes against blender's mentality to avoid a rainbow UI, better just have one accent color and maybe use this to communicate something like it's used for blender's workspacetools (where green is used as "add" and red as "remove" etc.).

I wouldn't recommend bothering to convert the existing icon set, they aren't well made and we don't need both types of icons, better to just support drawing regular interface icons in the viewport.

**Comment by Cheaterman** [comment]
I suppose this issue will be best used for tracking code progress on implementing the new layout for now, and another issue could be made for artists to suggest new icons? My thinking goes, once the layout is implemented, changing assets should be trivial?
