### ISSUE TITLE
[BUG] Construction circles not visible

### ISSUE THREAD

**Issue by BrCadfael** [hlorus/CAD_Sketcher#162]
### Contact Details

policebox@charter.net

### Description

When I set the Construction check on a circle, it disappeared.  Turning off the Construction check restores the circle.  I verified that the visible check was set the whole time.  My guess is that it doesn't know how to draw a construction circle.

### Addon Version

0.22.6

### Blender Version

3.1.2

### What platform are you running on?

Windows

**Comment by BrCadfael** [comment]
Additional information.  The circles do appear if you zoom into them.  The problem appears to be connected to the size of the circle on the screen.  A large construction circle will be visible, a smaller one may not be.  There is a transition point where the circle "materializes" as you zoom in and "dematerializes" when you zoom out.  On my screen that happens when the circle is about a centimeter across.  The issue doesn't appear to affect lines at all.  Construction lines are always visible.

**Comment by hlorus** [comment]
Looks like a glitch with the opengl dashed shader. I can reproduce this but it's usually not a problem for the scale i'm working with.

**Comment by amrsoll** [comment]
For some context
![image](https://user-images.githubusercontent.com/24782867/183736182-6c19b84a-444f-4427-9fbc-21bfedd16b45.png)

![image](https://user-images.githubusercontent.com/24782867/183736251-c422f95f-435f-4b84-998b-e58c35f89e6a.png)

![image](https://user-images.githubusercontent.com/24782867/183736307-82f96117-55dd-4dee-a507-42d8a564d9cb.png)

**Comment by jvenborg** [comment]
Yep, that has become an issue for me as well. Solid lines in circles are all fine, but construction lines will become invisible. In my current sketch, the diameters of the circles are 2 and 5 mm, respectively. Version 0.25.0.

**Comment by Miguel-Rodrigues** [comment]
Same thing happens here:


![Image](https://github.com/hlorus/CAD_Sketcher/assets/10254384/a295209b-1362-4334-9962-fd6cc2b8c32a)


![Image](https://github.com/hlorus/CAD_Sketcher/assets/10254384/1c1ca8b2-6644-450f-98d0-6f0c2c1217dc)

Windows 10
Blender 3.5.1
CAD Sketcher 0.27.1
