### ISSUE TITLE
[BUG] Vertical/horizontal distance constraint causes jumping

### ISSUE THREAD

**Issue by BaoNTGH** [hlorus/CAD_Sketcher#191]
### Description

Repro step:
1. Add sketch
2. Add line
3. Select 2 end points of the line
4. Alt-H (horizontal) or Alt-V (vertical)

Expected:
Horizontal or vertical constraint is added with current distance value without moving the points of the line.

Actual:
Different distance value was provided that caused the line jumps
![image](https://user-images.githubusercontent.com/29285869/174172105-6623fa2c-1172-4ca6-b111-ca54c657208e.png)

![image](https://user-images.githubusercontent.com/29285869/174172145-9abffe72-5e5e-49e7-8102-2e908c38d983.png)

### Addon Version

latest

### Blender Version

3.1.2

### What platform are you running on?

Windows

**Comment by TheMakerTales** [comment]
Ya I've experienced the same when sketches have zero or lake constraints

**Comment by amrsoll** [comment]
It looks like the horizontal/vertical distance constraints use the length of the line as the value for the constraint, instead of using the projection of the line onto the given axis for the measurement.
