### ISSUE TITLE
[BUG] CAD Sketcher not installing

### ISSUE THREAD

**Issue by ztitchez** [hlorus/CAD_Sketcher#199]
### Contact Details

darkkhris@gmail.com

### Description

so I tried to install CAD Sketcher and it was giving me this message, I'm not good at making reports so I opted to attach image and my system info, also another issue, I installed blender from flatpak and when I tried to open it, it was logging me out of session so I reinstalled from apt and got to this error

A bug happened
![Screenshot from 2022-06-21 12-10-37](https://user-images.githubusercontent.com/33461638/174869567-0222f9d8-89e1-47e9-bd3d-45fdb7e43a6d.png)
[system-info.txt](https://github.com/hlorus/CAD_Sketcher/files/8951614/system-info.txt)
!

### Addon Version

0.23.1

### Blender Version

2.82

### What platform are you running on?

Linux

**Comment by hlorus** [comment]
Hey there, the addon is unfortunately not supported for Blender versions below 2.92.
