### ISSUE TITLE
Ability to move all selected parts of a sketch

### ISSUE THREAD

**Issue by TheMakerTales** [hlorus/CAD_Sketcher#202]
The ability to move multiple selected entities at a time.

**Comment by TheMakerTales** [comment]
This issue has been given a $100 bounty!
Find out more about bounties here: [https://www.cadsketcher.com/cad-sketcher-bounty-board](https://www.cadsketcher.com/cad-sketcher-bounty-board)

**Comment by Shaddy-ElDesouky** [comment]
Upvote, also adding copy option while move, copy paste option too.

**Comment by amrsoll** [comment]
See #254
