### ISSUE TITLE
Dark and Light click not work through Edit > Preferences on Add-ons [BUG]

### ISSUE THREAD

**Issue by mac4kent** [hlorus/CAD_Sketcher#216]
### Contact Details

Dark, Light bug on Edit - Preferences on Add-on tab 

### Description

<img width="392" alt="image" src="https://user-images.githubusercontent.com/4253305/177220050-b4e5226b-2cff-4fc4-bd99-931641795773.png">

Dark and Light bug not work on Blender 3.2.0 and 3.2.1
![image](https://user-images.githubusercontent.com/4253305/177219691-92ee7ee7-d789-49b7-ad94-e190f8120c2e.png)

then next click Dark
![image](https://user-images.githubusercontent.com/4253305/177219670-613fdf12-b607-4341-a0fb-291f2a175a52.png)

### Addon Version

0.24.0

### Blender Version

3.2.0 and 3.2.1

### What platform are you running on?

Mac OSX

**Comment by hlorus** [comment]
Did you already install the solver module whwn this error happened?

**Comment by mac4kent** [comment]
let me check if your update time/date.

**Comment by mac4kent** [comment]
did not resolve. I already click install button yesterday same time 0.24.0 add-on yesterday (July 4, 2022)
<img width="2968" alt="image" src="https://user-images.githubusercontent.com/4253305/177320544-99c600e5-0cb2-44f0-897e-58d0fc3e61d4.png">

**Comment by mac4kent** [comment]
My screenshot record. https://youtu.be/9XgesKLgcks you can see. I am not good english explain text.

**Comment by hlorus** [comment]
Could you check the console for any messages? https://hlorus.github.io/CAD_Sketcher/advanced/#console-output

**Comment by mac4kent** [comment]
Linux/Mac is not support because of Linux is a Windows. Mac is not Windows.
I can tell C:/ is not support on Mac only.
Mac is not support (CTRL+ALT+T) never support.
AppData not there.

You give me link there many is not match on Mac. They said (Linux/Mac) is not support. 
Must separate (Windows / Linux / Mac) because Mac is very special direct not Linux.

<img width="3200" alt="image" src="https://user-images.githubusercontent.com/4253305/177336649-30c4e844-27d6-4a20-97a1-5df10d7ba15b.png">

<img width="1346" alt="image" src="https://user-images.githubusercontent.com/4253305/177336280-306b58ee-bf55-4dea-b233-def638d1cbec.png">


<img width="3200" alt="image" src="https://user-images.githubusercontent.com/4253305/177337175-31176b65-b607-44e9-b5a9-964b40d61096.png">

**Comment by mac4kent** [comment]
I am wait for you answer

**Comment by hlorus** [comment]
Could you try with the latest version from github?

**Comment by mac4kent** [comment]
I still can't read black line plane floor after click.
https://youtu.be/zCarMBGwUwE

**Comment by amrsoll** [comment]
Hey @mac4kent

On your last video, everything looked mostly normal. ( The "solver Module" did not install correctly though)

We know that Mac an Linux are very different platforms, but the program is mostly OK for both platforms. Are you able to start your Blender program in a terminal? 

> The `AppData` example is just an example, it could look different for you

When you select the workplane, they disappear. This is normal. You can now start making lines, circles etc... Your interface is original, and I cannot see the buttons, but here are the shortcuts:

> https://hlorus.github.io/CAD_Sketcher/tools/

|Key|Modifier|Action|
|:---:|---|---|
|ESC|-   |Activate Tool: Select|
|P|-   |Invoke Tool: Add Point 2D|
|L|-   |Invoke Tool: Add Line 2D|
|C|-   |Invoke Tool: Add Circle|
|A|-   |Invoke Tool: Add Arc|
|R|-   |Invoke Tool: Add Rectangle|
|S|-   |Invoke Tool: Add Sketch|
|Y|-   |Invoke Tool: Trim|

**Dimensional Constraints:**

|Key|Modifier|Action|
|---|---|---|
|D|Alt   |Distance|
|V|Alt   |Vertical Distance|
|H|Alt   |Horizontal Distance|
|A|Alt   |Angle|
|O|Alt   |Diameter|
|R|Alt   |Radius|

**Geometric Constraints:**

|Key|Modifier|Action|
|---|---|---|
|C|Shift   |Coincident|
|V|Shift   |Vertical|
|H|Shift   |Horizontal|
|E|Shift   |Equal|
|P|Shift   |Parallel|
|N|Shift   |Perpendicular|
|T|Shift   |Tangent|
|M|Shift   |Midpoint|
|R|Shift   |Ratio|

**Comment by mac4kent** [comment]
@amrsoll 
You still don't understand.
Deaf/Blind I have low vision and I unable to see too black edge. Please add feature so I able to change other color than black edge.
I am not talk about hotkey , shortcut. Only focus color to fix.

**Comment by mac4kent** [comment]
Look at black edge I totally can't read. 
https://imgur.com/Y3cmy5z
See picture. 3D Viewer

**Comment by amrsoll** [comment]
Ah, I see, my bad, I am looking into it

**Comment by mac4kent** [comment]
Good finally you understand.

**Comment by amrsoll** [comment]
Well, the color you are looking for is **Highlight**

![image](https://user-images.githubusercontent.com/24782867/183740324-f04dfaa7-437c-4ee1-8ba4-edd673de4ccc.png)

![image](https://user-images.githubusercontent.com/24782867/183740504-2ff6ab59-d007-4492-b3d3-ecdbce3e71a4.png)

Also I think the original bug has been fixed :) So we can close this issue?

**Comment by amrsoll** [comment]
> Look at black edge I totally can't read.
https://imgur.com/Y3cmy5z

Also in your image, there is nothing inside the window, which explains why you cannot see anything :) You need to add something, which is why I gave you the shortcuts to add elements

**Comment by mac4kent** [comment]
You already miss whole preferences I am show you again. 
<img width="1644" alt="image" src="https://user-images.githubusercontent.com/4253305/183741512-1ce47cfa-e8c7-428e-9630-2c1511139fd1.png">

I already setting there and still black after click plane I unable to see.

**Comment by mac4kent** [comment]
Let me update again on CAD there update 2 hours ago.

**Comment by amrsoll** [comment]
I don't see any black edges anywhere ... Could you draw a red circle around what you have problem seeing exactly?

**Comment by amrsoll** [comment]
do not worry about the new updates, they are not related to the colors

**Comment by mac4kent** [comment]
<img width="2556" alt="image" src="https://user-images.githubusercontent.com/4253305/183742129-a4cd09aa-4ee2-43ea-bf37-b08883870270.png">

I see they add feature "Inactive" so I change from black to purple.

**Comment by mac4kent** [comment]
Default I just change black to green.
There same I will check later after render is finish.

**Comment by mac4kent** [comment]
I will wait for them to fix color full color without miss.

**Comment by amrsoll** [comment]
> Look at black edge I totally can't read. 
https://imgur.com/Y3cmy5z See picture. 
3D Viewer

Please **draw red arrow** or **draw red circle around the black edge** and send it here.

I do not understand what it is you are trying to show me.

**Comment by mac4kent** [comment]
Ok after render is finish then I will show you on youtube. I can do screen record on my iMac.

**Comment by amrsoll** [comment]
From you previous video, here https://youtu.be/zCarMBGwUwE?t=300

You are circling the mouse around _nothing_. you just need to add new elements to the sketch you created :)

Example, try to press <kbd>L</kbd> and click somewhere on the screen :wink:

**Comment by mac4kent** [comment]
Did you mean Push the Shift + Command + 5 then push the L key? (Mac)

**Comment by amrsoll** [comment]
You can also find the buttons to add elements if you press the arrow on the left of your 3D view

![image](https://user-images.githubusercontent.com/24782867/183745325-e00adc81-4ee1-4429-a158-8163d4a4d968.png)

You will see buttons like these ones for CAD Sketcher

![image](https://user-images.githubusercontent.com/24782867/183745409-91837dba-ab79-4953-a136-f4ea7895332b.png)

**Comment by amrsoll** [comment]
> Did you mean Push the Shift + Command + 5 then push the L key? (Mac)

Nope, just <kbd>L</kbd> then use your mouse to click in the 3D view :)

**Comment by mac4kent** [comment]
How did you get red arrow?
No not talk about tools (you show me picture on left side). Focus on plane (floor) color.
Let me open Affinity Designer.app to show you.
1. There 3 plane and mouse over on plane become gray that one and I will click.
https://imgur.com/EwJcQjf

2. After click and I unable to see too black edge line of plane
https://imgur.com/HzGcCOX

**Comment by amrsoll** [comment]
The plane disappeared. It is normal. Now you are inside the sketch

![image](https://user-images.githubusercontent.com/24782867/183748781-a9f07f68-cf57-4fe3-863d-b434c246d0f0.png)

![image](https://user-images.githubusercontent.com/24782867/183748881-6db39ceb-5f0f-4f2d-9282-89233e1d872d.png)

Now you need to add stuff to your sketch. 

I can recommend to follow the [tutorial](https://hlorus.github.io/CAD_Sketcher/getting_started/#create-a-sketch) 

> How did you get red arrow?

My screen capture program has that feature

**Comment by amrsoll** [comment]
I am going to close this issue now, as the discussion is completely off the original topic.

**Comment by amrsoll** [comment]
If you need help in general, you might have more luck on the official chat of CAD Sketcher :) 

https://discord.com/channels/882152824249667594/891060540498124800

**Comment by mac4kent** [comment]
Did you mean "My screen capture program has that feature"
look at this Keyboard shortcut 
<img width="827" alt="image" src="https://user-images.githubusercontent.com/4253305/183750546-ff6954ba-f692-4cd6-bb11-b8fa6f11ae78.png">

**Comment by amrsoll** [comment]
We do not have the save system. I don't use Mac.

**Comment by mac4kent** [comment]
Sigh

**Comment by mac4kent** [comment]
@amrsoll 
We know that Mac an Linux (There is NOT TRUE!!!!!!!!)
Mac and Linux is bigger different.
Linux is Windows.
Mac is Macintosh.
You know about Mac then you must have Mac computer like iMac, PowerBook Pro is Mac, MacPro is Mac.

**Comment by mac4kent** [comment]
C:>/ is Dos and Windows and Linux.
Volumes is Mac.

**Comment by mac4kent** [comment]
kentdavis@Kents-iMac / % cd /Volumes; ls
Kent Davis
kentdavis@Kents-iMac /Volumes %

**Comment by amrsoll** [comment]
No Kent,
That is not what I wrote.
You are wrong about how Linux, Mac and Windows work.

I do not think you are doing it on purpose, but you are being difficult to help.

I am not going to answer further.

Good luck with using CAD sketcher for your project.

**Comment by amrsoll** [comment]
@mac4kent 

> We know that Mac an Linux (There is NOT TRUE!!!!!!!!)
.
Actually you seem to be right. I made a typo.

Mac *and* Linux are very different.
