### ISSUE TITLE
[BUG] register_class already registered 

### ISSUE THREAD

**Issue by ralfbiedert** [hlorus/CAD_Sketcher#224]
### Description

Enabling CAD Sketcher gives an exception:

![Screenshot_4](https://user-images.githubusercontent.com/301288/179421559-7b7f00ea-8f3f-4657-9587-c4ce6db73b90.png)

### Addon Version

0.24.0

### Blender Version

3.2.0

### What platform are you running on?

Windows

**Comment by hlorus** [comment]
Thanks for reporting,
Does this also happen when you restart blender after the installation? You might also try the latest version from github.

**Comment by ralfbiedert** [comment]
> Does this also happen when you restart blender after the installation? 

Hm, yes, I've just opened up Blender again and now it seems to work. Trying the latest `main` gives this though:

![image](https://user-images.githubusercontent.com/301288/179452453-cfedeb3a-21fc-40b0-81f3-8a0e57d62102.png)

**Comment by hlorus** [comment]
Ahh i see, should be fixed by: https://github.com/hlorus/CAD_Sketcher/commit/2d6f60992087e0507a01d5b03761a12a2439c42b

**Comment by ralfbiedert** [comment]
Thanks!
