### ISSUE TITLE
[BUG] Regression: Weird behaiviour when solidifying converted sketch

### ISSUE THREAD

**Issue by hlorus** [hlorus/CAD_Sketcher#225]
### Description

Some vertices are extruded in the wrong direction.

Introduced in https://github.com/hlorus/CAD_Sketcher/commit/588f51d256cac7bfc6cb16760456fb3e898d4961.

### Addon Version

588f51d256cac7bfc6cb16760456fb3e898d4961 - latest

### Blender Version

all

### What platform are you running on?

Windows

**Comment by hlorus** [comment]
https://youtu.be/e1okzVLP2i0

**Comment by TrabacchinLuigi** [comment]
saw the video, seem like a winding problem to me, vertex in most cases need to be laid out in a precise order, probably blender sort them out automatically and those generated aren't, just a wild guess
