### ISSUE TITLE
[BUG] Cannot move or drag anything once I have 3 fixed points

### ISSUE THREAD

**Issue by dreen24** [hlorus/CAD_Sketcher#227]
### Contact Details

dreen24@gmail.com

### Description

Whenever I create 3 fixed points I can no longer move anything. Once I change one of the fixed points to no longer be fixed I can move and adjust things again.

### Addon Version

0.24.0

### Blender Version

3.2.1

### What platform are you running on?

Linux

**Comment by hlorus** [comment]
Could you share the file or a screenshot of the setup? Does the solver say that it's failing?

**Comment by hlorus** [comment]
Great to hear it's working now. Feel free to reopen if the problem appears again.
