### ISSUE TITLE
Cannot copy a Sketch into an other project

### ISSUE THREAD

**Issue by Byvm815** [hlorus/CAD_Sketcher#228]
### Contact Details

2529025686@qq.ccom

### Description

I 'm no very good at English, with Chinese :
当我把一个Sketcher绘制的物体拷贝到另一个文件时，它的数据丢失了。

### Addon Version

0.24.0

### Blender Version

3.1.2

### What platform are you running on?

Mac OSX

**Comment by Byvm815** [comment]
I read the roadmap, it will be true on release 2.0.0

**Comment by exegetor** [comment]
google translate of the Chinese:
"When I copy an object drawn by Sketcher to another file, its data is lost."

Perhaps you copied only the mesh?  If so, the mesh will not carry the Sketcher data with it.

**Comment by hlorus** [comment]
Ahh thanks for translating. Sketcher data is currently stored on the scene object so you would have to copy the whole scene to another file if you want to reuse the sketcher data.

**Comment by Byvm815** [comment]
@exegetor 
You are right. I know what happened in the next day. And I'm sorry to   you(@hlorus ) for my slowness.
你说得对，我在第二天就明白怎么回事了,抱歉这么晚才回复你。

**Comment by Byvm815** [comment]
> Ahh thanks for translating. Sketcher data is currently stored on the scene object so you would have to copy the whole scene to another file if you want to reuse the sketcher data.

@hlorus 
Thank you very much for your help
非常感谢你的帮助

**Comment by exegetor** [comment]
@hlorus, can you drop the bug label and relabel it Documentation?   I think this ought to be in the manual for 1.0

**Comment by hlorus** [comment]
> @hlorus, can you drop the bug label and relabel it Documentation?   I think this ought to be in the manual for 1.0

I agree, however are you not able to edit the issue? I should look into github permissions then.

**Comment by exegetor** [comment]
That is correct; I could find no means of relabeling this.  Thanks!
