### ISSUE TITLE
Slight inaccuracy in docs

### ISSUE THREAD

**Issue by McSimKammerer** [hlorus/CAD_Sketcher#230]
https://hlorus.github.io/CAD_Sketcher/tools/#workspacetool-access-keymap
If I understand it correctly there is inaccuracy in keymap table - numerical constraints must be used with Alt, not Shift.
Sorry in advance if I'm mistaken.
Thank you very much for your work!

**Comment by hlorus** [comment]
Thanks for the hint, i've updated the docs
