### ISSUE TITLE
Error when installing plug-ins

### ISSUE THREAD

**Issue by JohnsonWu47** [hlorus/CAD_Sketcher#231]
I have installed blender from the msi file on the official website, tried to run blender with administrator privileges, and all dependencies have also been installed, but it is shown as follows:
![`JC(1}}QGS5)1 778KJWB](https://user-images.githubusercontent.com/109790782/180396877-9e75569b-70ca-4e81-a26c-aebac398e628.png)
![image](https://user-images.githubusercontent.com/109790782/180397120-22ecfb4b-16f4-441b-992f-73ba8cd9c487.png)

**Comment by hlorus** [comment]
Hey, thanks for the report. This should already be fixed since: https://github.com/hlorus/CAD_Sketcher/commit/3ab88343eb61b11d90940fbd14b16e14e02a79c3
