### ISSUE TITLE
[BUG] Sketch is in "Unknown Failure" status

### ISSUE THREAD

**Issue by abergmeier** [hlorus/CAD_Sketcher#239]
### Contact Details

abergmeier@gmx.net

### Description

I was creating a sketch and suddenly it displayed "Unknown Failure" without highlighting any constraints.

### Addon Version

0.24.0

### Blender Version

3.2.1

### What platform are you running on?

Linux

**Comment by hlorus** [comment]
Hey, thanks for the report. "Unknown Failure" is a valid state of the solver and basically means it cannot report why the system cannot be solved. Therefor this isn't an actual bug. I'd suggest to just undo the change whenever the solver gets to that state and try to simplify the sketch.
