### ISSUE TITLE
[BUG]: unable to create sketch

### ISSUE THREAD

**Issue by michael-barrow** [hlorus/CAD_Sketcher#242]
**Issue:**
Crash after adding new sketch. Cannot edit a sketch.

**Version:**
Blender: 3.2.1 or 3.0.1. with CAD Sketcher 0.24.0, Ubuntu 22.04 (Fresh install)

**Steps to reproduce**
ctl+shift+a, select any option or tool from within blender, sketch disappears, with no ability to add any elements to sketch.

**Example**

![CADCAMIssueAug6_2022](https://user-images.githubusercontent.com/20428997/183268658-8253b170-71d0-4c24-8830-2db2a89054fc.gif)

Dependencies are installed. No other addons besides those shipped with 3.2.1 or 3.0.1
![CADSketcherPluginConf](https://user-images.githubusercontent.com/20428997/183268786-42ceefea-2574-4ee9-9250-23d7591cb7b7.png)

**Comment by exegetor** [comment]
when you select the workplane, it has to be highlighted (white).  It's not clear that this is happening here.  If you click without a highlighted outline, it does not register the click (interprets as a cancel)

**Comment by michael-barrow** [comment]
Thanks for the response @exegetor. It seems it is not possible for me to select the workspace, it simply vanishes as in the example .gif when moused over (highlighted white) and left clicked.

**Comment by amrsoll** [comment]
I agree with exegetor. As far as I can see from the video you are moving your mouse around to fast to be selecting a workplane.

It might help you to open the side panel to have a view of the active sketches.

![image](https://user-images.githubusercontent.com/24782867/183722495-e9cfdb83-0ab9-444b-bf3c-35d9d02ca32f.png)

You have to hover the selector closer to the black borders of the gray squares, then the gray square (workplane) should be highlighted in white.

Closing for now, unless you continue struggling with this, feel free to reopen.
