### ISSUE TITLE
Introduce formatting guidline

### ISSUE THREAD

**Issue by hlorus** [hlorus/CAD_Sketcher#248]
Automatic formatting can go along way to improve readability of the code and make our lives easier. Following are the steps to get there.

- [x] Evaluate and decide on options -> Black
- [x] Batch format the project 
- [x] Add guidline to documentation 
- [x] Add github action to check formatting on PRs

**Comment by hlorus** [comment]
Personally i would go with black as a formatter to keep it simple and avoid trouble with different configurations between contributors.

**Comment by laundmo** [comment]
seconding the Black idea. Black has the great advantage of being opinionated and consistent - theres only one parameter to adjust which is max line length and i would leave that at default.

This helps tremendously for preventing inconsistencies across contributors and PRs.

I also recommend using https://pre-commit.com/ as part of the setup to reduce the amount of github action checks failing on formatting or other linters.

**Comment by hlorus** [comment]
Okay, let's go with black for now.

**Comment by hlorus** [comment]
All done.
