### ISSUE TITLE
Mac on Command, Option (ALT), Control, Shift August 13, 2022

### ISSUE THREAD

**Issue by mac4kent** [hlorus/CAD_Sketcher#250]
I notice no one body answer about FEEDBACK so I put this here.

Feature this CAD Sketch on Blender 3.2.2 for Mac. Do not use Windows.
I see you made Keymap code on CAD Sketch and I am show you screenshot on Mac.
https://imgur.com/9FiQte1

Your code is https://imgur.com/n0Y6xSh

https://support.apple.com/en-us/HT201236

**Comment by hlorus** [comment]
Not exactly what this is about. Afaik mac has an alt key.

**Comment by mac4kent** [comment]
Allright
Macintosh        |    Windows
Command       =       CTRL
Option (ALT)   =        ALT
Control            =          ... ? ? ?

**Comment by amrsoll** [comment]
In your Apple support link, it does say that Ctrl = Control on Mac

Control = CTRL

![image](https://user-images.githubusercontent.com/24782867/185994256-762e90da-2c83-4747-b954-5d731cbe0334.png)

**Comment by mac4kent** [comment]
Yes 
Mac is Control (CTRL) = Windows is ???
Mac is Command = Windows is CTRL.

**Comment by amrsoll** [comment]
No, Mac Control = Windows Ctrl

![image](https://user-images.githubusercontent.com/24782867/185997860-2a7bdc97-ad89-45a9-a5e4-29f1f1b9f47a.png)

**Comment by mac4kent** [comment]
I ask you do you have your own Macintosh computer?

**Comment by mac4kent** [comment]
You are wrong answer.
Mac Command + C is copy
Mac Control + C is nothing 
Mac Command + V is paste.
Mac Control + V is nothing.
Windows CTRL + C is Copy
Windows WindowKey + C is nothing
Windows CTRL + V is Paste
Windows WindowKey + V is nothing.
Mac is not same as Windows.

**Comment by mac4kent** [comment]
https://support.apple.com/en-us/HT201236#:~:text=Command%2DC%3A%20Copy%20the%20selected,for%20files%20in%20the%20Finder.

**Comment by mac4kent** [comment]
![image](https://user-images.githubusercontent.com/4253305/186025937-a388e5a9-e742-45a6-8830-397d1d6dbe2d.png)

**Comment by amrsoll** [comment]
What is your problem then? Are you not able to use the shortcuts?

**Comment by mac4kent** [comment]
You did not answer. I am ask you question "Do you have your own Macintosh computer?"

**Comment by mac4kent** [comment]
I see you hate Mac! Because you not want work on Mac keyboard. You do love Windows only.

**Comment by hlorus** [comment]
This doesn't have anything to do with the developers opinion of  mac. Your bug report doesn't clearly describe the problem. It's not clear if this is just about the documentation or if a shortcut is broken. Also the links to the images no longer work.

**Comment by mac4kent** [comment]
Screencast Key Add-Ons already fix a bug 4 months ago for Blender 3.4.1 support for Mac.

**Comment by mac4kent** [comment]
Yes.
