### ISSUE TITLE
Add copy/paste operators

### ISSUE THREAD

**Issue by hlorus** [hlorus/CAD_Sketcher#255]
Allows to copy selected entities and their constraints and paste them at a later point.
This also has to work after the original entities are deleted.

**Comment by therealjacobbrauer** [comment]
> Allows to copy selected entities and their constraints and paste them at a later point.
> This also has to work after the original entities are deleted.

Does this mean that you are going to be copying selected sketch entities and their constraints and pasting them, and then deleting the original ones without losing the copies, 

**-or-**

 just copying and then deleting the original ones, and then some time down the road pasting the saved copies that have not been visible the rest of the time, since the originals were deleted?

**Comment by hlorus** [comment]
> > Allows to copy selected entities and their constraints and paste them at a later point.
> > This also has to work after the original entities are deleted.
> 
> Does this mean that you are going to be copying selected sketch entities and their constraints and pasting them, and then deleting the original ones without losing the copies, (this is what solid works supports)
> 

Yes, this one. It would simply take a snapshot when copying. After that there's no connection to the original entities.

**Comment by therealjacobbrauer** [comment]
Excellent. Would a option for a start/end point of the copy operation be okay to proceed with as well? 

also is an option desired for the copy operation so that there is a way to do copy or move entities, like in a text editor this would be referred to as copy or (cut = move) entities?

**Comment by hlorus** [comment]
> Excellent. Would a option for a start/end point of the copy operation be okay to proceed with as well? 
> 
> also is an option desired for the copy operation so that there is a way to do copy or move entities, like in a text editor this would be referred to as copy or (cut = move) entities?

Such things would be great but i advise to keep it simple to start with and then add additional features once a basic version has been reviewed/merged.
