### ISSUE TITLE
Edits to mesh curve resolution don't result in any change to the actual mesh curve resolution

### ISSUE THREAD

**Issue by paynterf** [hlorus/CAD_Sketcher#262]
### Contact Details

paynterf@gmail.com

### Description

With the new 0.25 update, I tried changing the 'mesh curvature' value in a new sketch.  The initial change (from 12 to 50 in my case) works, but subsequent edits to change the curvature do not succeed.  When I try to us the sketch update button (the curved arrows), I get a popup with a bunch of python errors noted.
![Screenshot 2022-08-20 105813](https://user-images.githubusercontent.com/4013547/185753110-91a7302b-a6ab-4f84-834e-562ec55f018d.jpg)
![Screenshot 2022-08-20 105939](https://user-images.githubusercontent.com/4013547/185753128-86673735-40e6-4fda-b8c6-9c3c3bdd5e69.jpg)
![Screenshot 2022-08-20 110004](https://user-images.githubusercontent.com/4013547/185753160-7cb2f8f4-859a-451a-ad80-7f4408f621a3.jpg)

### Addon Version

0.25

### Blender Version

3.2.1

### What platform are you running on?

Windows

**Comment by paynterf** [comment]
This may have been a user problem.  At some point I discovered I had selected a view that was orthogonal to the workplane (NUM3 instead of NUM7).  Once I figured this out, things started working again.  No idea though why I was able to draw a circle and a line that looked normal, even though I was drawing it orthogonal to the workplane!

**Comment by hlorus** [comment]
This might also have been caused because the object was in editmode. As the object data will be written once you leave editmode other changes might get overwritten.
