### ISSUE TITLE
Added a radius dimension to a circle, but the entity type shows as 'SlvsDiameter'

### ISSUE THREAD

**Issue by paynterf** [hlorus/CAD_Sketcher#263]
### Contact Details

paynterf@gmail.com

### Description

I added a circle entity to a new sketch and selected ALT+R to add a radius dimension.  I got the normal radius depiction and was able to enter a radius, but the dimensional entity shows as 'SlvsDiameter', not 'SlvsRadius'.  With just this information I can't tell whether the circle has a radius of 15mm or a diameter of 15mm.

Also, I don't seem to be able to select the dimension arrow so I can move it around like I could with 0.24

### Addon Version

0.25

### Blender Version

3.2.1

### What platform are you running on?

Windows

**Comment by amrsoll** [comment]
This is probably only applicable when using the shortcut.

The name is created at the same time as the constraint and you can edit it from there.

A quick solution is to name all the constraints you use in order to avoid confusions :)

Otherwise, I do have a potential solution and PR coming up.
