### ISSUE TITLE
Feature Request: Copy & Paste sketch entities

### ISSUE THREAD

**Issue by Shaddy-ElDesouky** [hlorus/CAD_Sketcher#273]
**Motivation / Existing Problem**
After selecting multiple entities in the sketch I couldn't copy them to paste them in another place inside the same sketch.

**Description**
For faster drawing, I need to select multiple entities and copy and paste them in the same sketch 

**Alternative Solutions**

**Mockup**

**Comment by hlorus** [comment]
Duplicate of #255
