### ISSUE TITLE
[BUG]Unknown failure

### ISSUE THREAD

**Issue by NoteToSelfFindGoodNickname** [hlorus/CAD_Sketcher#277]
### Contact Details

antoniocaroppos@gmail.com

### Description

I am trying to give a line and a point a distance contraint.

Here is a video what I tried:
https://www.youtube.com/watch?v=Qf80tlABOHY

Here is the blend file:
[intelligazethalter1.zip](https://github.com/hlorus/CAD_Sketcher/files/9470585/intelligazethalter1.zip)

### Addon Version

0.25.0

### Blender Version

3.2.2

### What platform are you running on?

Windows

**Comment by hlorus** [comment]
Unknown Failure isn't actually a bug. This simply means that the solver cannot find a solution and cannot actually report why it fails.

In your video it simply looks like it's overconstrained as you' ve constrained the width twice.
