### ISSUE TITLE
Line width not working on mac

### ISSUE THREAD

**Issue by mervenca** [hlorus/CAD_Sketcher#29]
**Description**
It may be a mac only thing, or resolution dependant- retina 13,3-inch (2560 × 1600)- the outer lines for sketching are too thin to use or select.
It's an issue from the start- really hard to activate a plane when creating sketch (basically pixel thin..should it also be selectable from the "face" of the plane, not only the edge?), hard to select sides etc to add constraints. 

**To Reproduce**
1. Using the add-on on Macbook air M1

**Expected behavior**
To select the planes and sketche's edges without a hassle.

**System Information:**
 - OS:  macOS Monterey 12.3.1
 - Blender Version: 12.3.1
 - Addon Version: 0.20.0
<img width="1181" alt="thin line blender" src="https://user-images.githubusercontent.com/54314292/164794087-5e451afd-58b5-45f1-b57f-8d2c109731cd.png">

**Comment by felixchenier** [comment]
I also have this problem on an Intel Mac on Catalina.

**Comment by MarkBTomlinson** [comment]
It is almost impossible to select work planes and entities on a 16" MBP.
The planes flicker as you hover over but hitting the hot spot is really hard.
I will try this on the PC later to see if it really is a HDPI issue.

**Comment by NoobTaco** [comment]
I am seeing this on the Mac Studio Ultra as well.

We need an option to change the line width.

**Comment by atsuyuki** [comment]
I found the same issue in another addon. This issue seems to be coming from OpenGL on Mac. It looks like a solution is indicated, but it is beyond me. I hope someone stronger can solve this problem.

[Line weight not working (MacOS)@MeasureIt_ARCH](https://github.com/kevancress/MeasureIt_ARCH/issues/6)

**Comment by gitblair** [comment]
While it is possible to choose a plane, it takes many attempts to get there.
The hovering that highlights the plane is not consistent. It feels very similar to attempting to choose anything other than the corner blocks. Also similar to the issue where the lines are too thin to hover over and select.

Mac OS 12.2.1
Apple M1
Blender 3.0.0
Addon 0.20.0

**Comment by hlorus** [comment]
This is now mostly resolved, see 4515af54884586dc6619915264d8bac01b651fec.
The only missing part is porting the display of dashed lines to the new shader.

**Comment by felixchenier** [comment]
It also seems to work on my mac 😃

**Comment by MarkBTomlinson** [comment]
Confirm it is work fine on my intel macBook now.
