### ISSUE TITLE
[BUG] Python error when drawing 2D shape

### ISSUE THREAD

**Issue by vit21ik** [hlorus/CAD_Sketcher#290]
### Contact Details

vvlasuk@gmail.com

### Description

Description
Added 0.25 from zip and cannot create sketch due to python  errors.
Create sketch and go to sketch mode.
Select any 2D tool (arc, rectange) place cursor to surface and I get this:
![Screenshot from 2022-09-03 12-49-51](https://user-images.githubusercontent.com/576012/188265896-d94d7c53-e4ab-4b2a-b23e-4d5f2417ea1b.png)

Addon Version
0.25.0

Blender Version
3.2.2

What platform are you running on?
Linux

### Addon Version

0.25

### Blender Version

3.2.2

### What platform are you running on?

Linux

**Comment by hlorus** [comment]
> Seems to die in icon_manager.py:73.

Why exactly are you assuming this?

**Comment by vit21ik** [comment]
>Seems to die in icon_manager.py:73.
Sorry, this line is not relevant to the bug. It seems like copy paste, my bad.

**Comment by hlorus** [comment]
No problem. Could you explain what "place cursor to surface" means exactly? I assume it's a native blender operator, are you invoking it from a menu/ shortcut?
Also does it happen while in object mode?

**Comment by vit21ik** [comment]
Steps are very simple: I selected 2d arc and clicked left mouse button anywhere in blender. As result - Report Error dialog as shown on attached screenshot.

**Comment by hlorus** [comment]
I cannot reproduce this unfortunately. Maybe you could try to completely remove the addon and re-install...

**Comment by amrsoll** [comment]
Let us know if you are able to reproduce it, preferably with a video showing the steps you took. You can reopen the issue :)
