### ISSUE TITLE
[BUG] wont let me get started

### ISSUE THREAD

**Issue by bradfoot** [hlorus/CAD_Sketcher#30]
**Description**
the add a sketch button shows the planes but you can't selection, when you click on one they disappear

**To Reproduce**
1. start blender
2. hit n to bring up the menu
3. and click on sketcher 
4. click on Add Sketch to bring up the planes
5. click on a plane and they go away

**Expected behavior**
it should make a new sketch and let me draw on it

**Screenshots**

**System Information:**
 - OS:  macbook air, m1 chip Mac OS 12.2.1
 - Blender Version: 3.1
 - Addon Version: 0.20.0

**Comment by felixchenier** [comment]
You have to select the outer line of the plane, but it is very difficult to do since these outer lines are so thin (#29).

**Comment by bradfoot** [comment]
thats a pain but i got it. hope somebody is working on that.
thanks

**Comment by physicsmazz** [comment]
Even when I click the outer line, which is next to impossible, it still doesn't start a sketch. Seems like it's possibly a Mac issue.

**Comment by hlorus** [comment]
This is a duplicate, see #29. Closing
