### ISSUE TITLE
Specific sketch solidify result not correct [BUG]

### ISSUE THREAD

**Issue by flufy3d** [hlorus/CAD_Sketcher#300]
### Contact Details

flufy3d@gmail.com

### Description

A bug happened! if you do a sketch like this
![image](https://user-images.githubusercontent.com/1730604/194952004-07e69780-b810-4d4f-a3d8-cd8ae212e47e.png)

the result  will be

![image](https://user-images.githubusercontent.com/1730604/194952144-556e9319-492c-4479-a5d6-78c675d5407c.png)

it's good when I remove the solidify modifer
![image](https://user-images.githubusercontent.com/1730604/194952258-cef6e0f4-80dc-4b76-a47b-cf05a85179b0.png)

but look at the left side ,it's very strange.

pls have a look on this

Thanks

### Addon Version

0.25.0

### Blender Version

3.3.0

### What platform are you running on?

Windows

**Comment by hlorus** [comment]
Closing as duplicate of #317

**Comment by flufy3d** [comment]
it's solved with 0.27 version  thanks
![image](https://user-images.githubusercontent.com/1730604/219785009-88fe0df7-afc9-42f8-a902-2579667ef534.png)
