### ISSUE TITLE
Bevel problems with circle hole

### ISSUE THREAD

**Issue by ggodlewski** [hlorus/CAD_Sketcher#301]
### Description

I have a problem with bevel.

The model I created is a 3x3x3 cube with a round hole drilled through it:

![Screenshot at 2022-10-12 14-02-41](https://user-images.githubusercontent.com/818238/195338474-78532ad7-8359-49a2-9360-04a45e914868.png)

I tried several different bevel width types and none seems to work correctly

With 10% one of the sides is different than the other:

![Screenshot at 2022-10-12 14-02-01](https://user-images.githubusercontent.com/818238/195338839-6da247f2-a6d5-4e14-bee7-b0a37d611eec.png)

With absolute 1m the bevel is not as big as I expect and there are some artifacts around circle.

![Screenshot at 2022-10-12 14-04-19](https://user-images.githubusercontent.com/818238/195338917-18c17c46-6b05-4286-a4ae-bf44d4061507.png)

I can bypass it with 2 sketches and boolean. However as a new user I must admit that the default behavior is strange. The most optimal one would be to select which edged to chamfer.

[cube_with_hole.blend.zip](https://github.com/hlorus/CAD_Sketcher/files/9764737/cube_with_hole.blend.zip)

### Addon Version

0.25.0

### Blender Version

3.3.0

### What platform are you running on?

Linux

**Comment by KoDeltaS** [comment]
Hello @ggodlewski and @hlorus, in my opinion everything is working fine. 
For an optimal bevel on a Cube, the Bevel modifier should be set to Offset, and in shading menù, you need to check Harden Normals. 
To avoid shading errors, it would be better to also modify the sketch as shown in the attached photo. 
![Screenshot 2024-09-02 215953](https://github.com/user-attachments/assets/ebdee5d7-9f56-4174-a05d-4b148995a7d1)

**Comment by hlorus** [comment]
Thanks a lot for the clarification @KoDeltaS! I'm going to close the issue then.

**Comment by ggodlewski** [comment]
![Image](https://github.com/user-attachments/assets/1ceec414-3497-4de7-b1dd-9a5776858f31)

Sadly, 3 years later this issue is still not fixed. No matter what I select: percent, offset, absolute, harder, not harden, I'm not able to make desired bevel on this object.
