### ISSUE TITLE
Increase constraints signs offset to Avoid misclicks

### ISSUE THREAD

**Issue by Pingear** [hlorus/CAD_Sketcher#304]
label:enhancement 

Hello)
Constraints signs are too close to nodes. For this reason, I constantly click on the constraints sign while trying to select a node. Please make a larger offset signs from nodes and from midlepoints to Avoid misclicks)

<img width="181" alt="image" src="https://user-images.githubusercontent.com/16469484/197370356-3cef7fe8-f8f2-4133-a0d6-28d165dda5f1.png">

<img width="363" alt="image" src="https://user-images.githubusercontent.com/16469484/197370444-4c819729-a61a-4341-be09-b5206c5d4a14.png">

**Comment by hlorus** [comment]
Thanks for the report, i assume the issue here is that the offset isn't scaled with the icon size. Fixed with https://github.com/hlorus/CAD_Sketcher/commit/c78d0f5c60bb61a3ba94eab6d0a88cf3a0df9b47

Feel free to reopen the issue if you're still having trouble
