### ISSUE TITLE
[BUG]  Supplementry Angle Unit Input Doing strange Things

### ISSUE THREAD

**Issue by TheMakerTales** [hlorus/CAD_Sketcher#310]
### Description

When you try and control/input an angel to a supplementary angle things go a little weird. @hlorus hase taken a small look and said that it looked slightly "random" might be a good call for @amrsoll to take a look at it as you have the most experience working on this area of the code,

<img width="1767" alt="Capture (1)" src="https://user-images.githubusercontent.com/103122109/200112902-56c8366a-5d0f-4254-b6cb-3219edfc4c5c.png">

### Addon Version

latest

### Blender Version

3.3

### What platform are you running on?

Windows

**Comment by TheMakerTales** [comment]
@amrsoll Any news on how this is going?

**Comment by amrsoll** [comment]
> @amrsoll Any news on how this is going?

Ah I shouldn't have self assigned this as I was starting a new job and.. well  life happened ><

Anyway, I will try to dedicate some time tomorrow. If I don't get to it then here is a pointer:

It seems to be a purely UI problem stemming from a change I made where the angle property _should always_ refers to the direct angle, then the UI would convert that value if it wants to display the complementary angle.

I will unassign myself until I am sure that I have actually a good chance of finishing this.

**Comment by amrsoll** [comment]
I still don't get how I missed this during tests, and I'm sorry this caused strain on the users and increased support
