### ISSUE TITLE
[BUG] Reversed normals

### ISSUE THREAD

**Issue by chiboreache** [hlorus/CAD_Sketcher#313]
### Description

`c+N` helps, but after edit sketch it's reverse it again

![2022-11-23x09:28:03](https://user-images.githubusercontent.com/16459251/203484799-8d9248e5-bbbc-4759-acd8-68bfcc8995fe.jpg)

### Addon Version

0.25.0

### Blender Version

3.3.1

### What platform are you running on?

Linux

**Comment by hlorus** [comment]
I'm assuming that the "Flip Normals" option of the solidify modifier should do the trick...?

**Comment by hlorus** [comment]
Closing as duplicate of #317
