### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mac4kent** [hlorus/CAD_Sketcher#319]
### Contact Details

Blender 3.5.0 crash guide January 12, 2023

### Description

Please check link more details.
https://developer.blender.org/T103817#1473301

### Addon Version

None

### Blender Version

3.5.0

### What platform are you running on?

Mac OSX

**Comment by hlorus** [comment]
Thanks for the report. As the crash isn't caused by the addon i'm going to close this.
