### ISSUE TITLE
Unable to install Cad Sketcher due to Solver Module [BUG]

### ISSUE THREAD

**Issue by ionutrogojan** [hlorus/CAD_Sketcher#329]
### Description

I was trying to install Cad Sketcher but I wasn't able to do so.
After some debugging, I got this logs:
```
CAD_Sketcher-main:{INFO}: Logging into: /tmp/CAD_Sketcher-main.log
CAD_Sketcher-main:{WARNING}: Solvespace module isn't available, only base modules registered
No module named 'py_slvs'
```
So I tried to install `py-slvs` but the pip package is not available on python 3.11, [please see here](https://github.com/realthunder/slvs_py/issues/4).

```
ERROR: Could not find a version that satisfies the requirement py-slvs==1.0.4 (from versions: none)
ERROR: No matching distribution found for py-slvs==1.0.4
```

So I installed python3.10 and the only available version on `py-slvs` here are `1.0.3` and `1.0.2`, and I was able to get the `1.0.3` version but going back to blender and running the `Install from PIP` still does not do anything.

I also looked into getting the `.whl` file for a manual install but there are no Linux files on `1.0.4` and all the files from the `1.0.3` version give me another error
```
ERROR: py_slvs-1.0.3-cp310-cp310m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl is not a supported wheel on this platform.
```
regardless of which file I try to install. Any pointers, solutions or advice is greatly appreciated. 

### Addon Version

0.25

### Blender Version

3.4.1

### What platform are you running on?

Linux

**Comment by hlorus** [comment]
Blender 3.4 is shipped with python 3.10. Python 3.11 isn't yet supported.
