### ISSUE TITLE
[BUG] Mesh rasterization seems to fail for complicated multi-part drawing

### ISSUE THREAD

**Issue by JosephCatrambone** [hlorus/CAD_Sketcher#35]
**Description**
When converting the following drawing (for finger cutouts in a block), the rasterized mesh does not match the shape of the drawing.

![Screenshot from 2022-04-23 18-47-38](https://user-images.githubusercontent.com/2160055/164952254-5cc4cc31-af3a-4b07-93bf-4b04f18472d2.png)

![Screenshot from 2022-04-23 18-48-18](https://user-images.githubusercontent.com/2160055/164952252-41ec2df2-335f-4868-be19-39222fc36e7a.png)

**To Reproduce**
1. Seems to happen when using arcs and midpoint constraints.  If I put the center of two arcs on a line and constrain the line to a midpoint (or to some distance from a point) then the solution that materializes is not expected.  Don't have a perfect approach to reproducing yet, but here's another example of a mesh that fails to rasterize:

![Screenshot from 2022-04-23 18-57-39](https://user-images.githubusercontent.com/2160055/164952514-c56e07e7-eeb7-4ccc-bc36-d7e9c55324fe.png)

![Screenshot from 2022-04-23 18-55-50](https://user-images.githubusercontent.com/2160055/164952516-9bc4ba16-978c-4ef3-83b6-c0947b9b087e.png)

**Expected behavior**
I would expect for a rounded arc to be 

**Screenshots**
Above

**System Information:**
 - OS: Linux Mint 20.04 
 - Blender Version: 3.1.0
 - Addon Version: 0.20.0

Blend File is Attached.

[hand_keyboard.blend.zip](https://github.com/hlorus/CAD_Sketcher/files/8548898/hand_keyboard.blend.zip)

EDIT: In the blend file the last drawing is not fully constrained, but it doesn't make a difference when I do add the remaining constraints.

**Comment by teddywaweru** [comment]
the issue could be the lines that are joining the arc, & the line between the arcs & the rectangles. I may be wrong but the developers may have set up the add-on to recognize everything apart from construction lines as potential geometry. So this affects  
![image](https://user-images.githubusercontent.com/57697272/165076886-bdd619f8-83a6-4699-94f8-44f5d970677e.png)

so in the above, the left doesn't have the joining line between the arc & rectangle, while the second one does. I'd say the base principle is that any **lines** in the sketch will be regarded as **active geometry** when generating the mesh. All distance constraints would be kept as construction lines

**Comment by hlorus** [comment]
@teddywaweru is right here, the converter tries to create closed bezier splines to figure out what area to fill, if there's a junction it has to guess which path to use as the main path. There's some more info in the docs, see:

https://hlorus.github.io/CAD_Sketcher/integration/

Anyway there seems to be another issue so leaving this open for now.

**Comment by JosephCatrambone** [comment]
Good catch.  I missed marking that as a construction line.  I wonder what a good way to communicate disconnected paths would be.  🤔  Could perhaps mark 'open' bezier curves in a different color.

**Comment by hlorus** [comment]
This seems to be working with recent versions when marking the inner lines as construction.
