### ISSUE TITLE
Installing version 0.27.1

### ISSUE THREAD

**Issue by inddigital-xtech** [hlorus/CAD_Sketcher#352]
Hello, it is an excellent tool,
When I install the 0.27.1 update, Blender works fine, but tells me that it just installed version 0.27.0.

It's not critical, but I'm not sure if it actually got updated.

![image](https://user-images.githubusercontent.com/84356154/222425515-ff8b237e-1807-4212-ae04-d9abb1cade32.png)

**Comment by TheMakerTales** [comment]
Oops, my bad. It's the right version but I renamed my test version rather than a new download directly from Git. I'll update this now.
