### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by JMGD-50** [hlorus/CAD_Sketcher#354]
### Contact Details

j.dohmen9@kpnplanet.nl

### Description

Hello, I installed CAD Sketcher add-on in Blender 3.4.1. on my iMac M1 (Apple silicon), MacOS Venture 13.2.1. I see that it is installed and I also enabled it but I do not see in the tools bar on the right side of the Blender screen, I already tried to restart the computer but did not help.
What to do, or is it not yet ready for M1's

### Addon Version

0.27.1

### Blender Version

3.4.1.

### What platform are you running on?

Mac OSX

**Comment by hlorus** [comment]
You'll have to install the solver module, see the chapter "Dependency Installation" here: https://hlorus.github.io/CAD_Sketcher/installation/
