### ISSUE TITLE
[BUG] Mesh creation fails when adding constraint

### ISSUE THREAD

**Issue by CobraA1** [hlorus/CAD_Sketcher#356]
### Contact Details

jeremiah.moss@gmail.com

### Description

This is how it looks before:

![Pasted image 20230305205854](https://user-images.githubusercontent.com/8573502/223009918-bb4e311a-1790-4fc6-89f8-a30d0375633c.png)

Added constraint to put lowest line on center point (midpoint constraint):

![Pasted image 20230305205928](https://user-images.githubusercontent.com/8573502/223009998-f63bfca9-f2f6-4f21-bdf6-fd811d88ceb3.png)

Completely ruins the mesh:

![Pasted image 20230305210001](https://user-images.githubusercontent.com/8573502/223010037-9812f0d0-f548-416a-b4f4-962aa3846121.png)

Blender file:
[Water bottle holder.zip](https://github.com/hlorus/CAD_Sketcher/files/10893996/Water.bottle.holder.zip)

### Addon Version

0.27.1

### Blender Version

3.4.1

### What platform are you running on?

Linux

**Comment by TheMakerTales** [comment]
Hmm, personally I have a feeling this might be asking a bit much form mesh modelling.
I changed your value of the diameter to 65.499 mm and pretty much every works as I guess your looking for.
![Capture](https://user-images.githubusercontent.com/103122109/223070261-8e903007-7610-46ce-acd7-94fddc839de6.JPG)

**Comment by hlorus** [comment]
This isn't a bug of the addon but simply a limitation of blender's bezier curves which will fail with overlapping edges.
