### ISSUE TITLE
[BUG]cannot import name 'slvs' from 'py_slvs'

### ISSUE THREAD

**Issue by BensonTerra** [hlorus/CAD_Sketcher#365]
### Contact Details

benson.terra@hotmail.com

### Description

After long time trying to install the Cad Sketcher, i had sucess. But another problem appeared.

Every time i try to create something on sketch i recieve message of error, and i searched inside the folder i didnt anything what it is generating this problem.

maybe this topic can help to understand what is happening.

![Captura de ecrã 2023-03-13 161403](https://user-images.githubusercontent.com/115477417/224762962-169d17a6-a3fe-4e98-9218-44e9bd600ee8.png)

### Addon Version

latest

### Blender Version

3.4

### What platform are you running on?

Windows

**Comment by hlorus** [comment]
This should now be resolved with the 1.0.6 version of the py-slvs library, see: https://github.com/realthunder/slvs_py/issues/7
