### ISSUE TITLE
will not install [BUG]

### ISSUE THREAD

**Issue by brushmake** [hlorus/CAD_Sketcher#37]
**Description**

**To Reproduce**
1. 
2. 

**Expected behavior**

**Screenshots**

**System Information:**
 - OS:  
 - Blender Version: 
 - Addon Version:

**Comment by hlorus** [comment]
Closing this as there's too less information to provide help. If you're still having truble you might wanna check out the discord help channel: https://discord.gg/XCa9yqVu or reopen the issue with more information provided.
