### ISSUE TITLE
[BUG]: Impossible to enable the plugin on blender 3.4.1 under ubuntu 22.04 (OSError: [Errno6] No such device or address)

### ISSUE THREAD

**Issue by KoolElmout** [hlorus/CAD_Sketcher#371]
### Description

A bug happened!.
Ubuntu 22.04
Blender 3.4.1
CAD_Sketcher Zip file : 0.27.1

When i try to enable the plugin, this report error appear:
![image](https://user-images.githubusercontent.com/94376004/227245058-4ce07999-257e-4ead-a979-7196cec32790.png)

### Addon Version

0.27.1

### Blender Version

3.4.1

### What platform are you running on?

Linux

**Comment by elmout31** [comment]
This is the last commit that is the problem. Inside the file : (Change the path accordingly to your installation)
/home/user/.config/blender/3.4/scripts/addons/CAD_Sketcher-main/utilities/logging.py
1) The line `import os` shall be changed by `import getpass`
2) The line 
`filepath = Path(gettempdir()) / (get_name() + f"-{os.getlogin()}" + ".log")`
shall be changed by
`filepath = Path(gettempdir()) / (get_name() + f"-{getpass.getuser()}" + ".log")`

3) relaunch blender and enjoy. 

(For the team, thank for your work, i cannot wait to have an equivalent of freecad inside blender for parametric creation and assembly).

**Comment by KoolElmout** [comment]
Thank for your answer. It is working now.

**Comment by KoolElmout** [comment]
It work, but i will let the team close the issue to incorporate the patch

**Comment by hlorus** [comment]
> This is the last commit ([90d7413](https://github.com/hlorus/CAD_Sketcher/commit/90d7413f47f601cad3fa1eefcea273147ccd3a0d)) that is the problem. Inside the file : (Change the path accordingly to your installation) /home/user/.config/blender/3.4/scripts/addons/CAD_Sketcher-main/utilities/logging.py
> 
>     1. The line `import os` shall be changed by `import getpass`
> 
>     2. The line
>        `filepath = Path(gettempdir()) / (get_name() + f"-{os.getlogin()}" + ".log")`
>        shall be changed by
>        `filepath = Path(gettempdir()) / (get_name() + f"-{getpass.getuser()}" + ".log")`
> 
>     3. relaunch blender and enjoy.
> 
> 
> (For the team, thank for your work, i cannot wait to have an equivalent of freecad inside blender for parametric creation and assembly).

Thanks for the solution!
