### ISSUE TITLE
[BUG] Repeatedly pressing force update gives the sketch Redundant Constraints.

### ISSUE THREAD

**Issue by bEPHen** [hlorus/CAD_Sketcher#374]
### Contact Details

bephen@gmail.com

### Description

When I have a fully defined sketch and press force update 3 times I get Redundant Constraints which is hard to solve.
![image](https://user-images.githubusercontent.com/80769834/227728767-2451f338-8cfc-4d34-a14d-959aee6a651a.png)
![image](https://user-images.githubusercontent.com/80769834/227728797-37e3361f-779a-452a-b578-bd216417e163.png)

[Bug  forcing update three times.zip](https://github.com/hlorus/CAD_Sketcher/files/11069367/Bug.forcing.update.three.times.zip)

### Addon Version

0.27.1

### Blender Version

3.4.1

### What platform are you running on?

Linux

**Comment by hlorus** [comment]
What happens when you remove the redundant constraints? Is it still fully defined?

**Comment by hlorus** [comment]
This doesn't seem like a bug, removing one of the redundant constraints solves the error.
