### ISSUE TITLE
[BUG] Precision on units for constraints too low (rounding happens)

### ISSUE THREAD

**Issue by alexfacciorusso** [hlorus/CAD_Sketcher#378]
### Contact Details

alexfacciorusso93@gmail.com

### Description

The precision assigned to the constraint's slider is too low. That causes constraints that should be shown precisely (e.g. 14.7mm) instead being rounded to the nearest unit (e.g. 15mm). When the slider is clicked, the text will show the full-precision value; see attached screenshots.

Even though the representation on the 3d view is correct (in that example, 14.70mm), I feel the precision should be increased in the panel's slider too.

![image](https://user-images.githubusercontent.com/4479527/231127964-d573ae20-cee5-4116-aafe-5c1a2e997285.png)
![image](https://user-images.githubusercontent.com/4479527/231128054-f8598bbd-ab34-4d83-bdd8-8755a2b302f9.png)
![image](https://user-images.githubusercontent.com/4479527/231128095-3514024d-2f29-4204-8b1a-8411a36c9f4b.png)

**EDIT**

I have noticed there is a "decimal precision" in the settings, which is honoured by the 3d view but not the property. I suppose the suggestion is to make the property to honour that precision too.

### Addon Version

latest

### Blender Version

3.5.0

### What platform are you running on?

Windows

**Comment by alexfacciorusso** [comment]
I could give this one a go and make a PR, if you all don't mind!

**Comment by hlorus** [comment]
Thanks for the report. It's obviously great if you wanna take a look at this however be aware that this might not be easily possible as the precision is set when defining the property.

**Comment by StrandedAlien** [comment]
Brave man, Alex, i wish you success. The low precision has been bugging CAD interested Blender users for a long time. I suggest you ask at the Blender dev forum https://devtalk.blender.org/ before you even start. My guess is it belongs to "Core Module". I had trouble with an imported 3D Maps data offset when i wanted to join the pieces. Found out it was due to Blenders low precision.
