### ISSUE TITLE
Switch active tool when entering & existing sketching mode

### ISSUE THREAD

**Issue by teddywaweru** [hlorus/CAD_Sketcher#38]
Could it be possible to switch the active tool that is currently selected to the Solvespace Select Tool when adding or editing the sketch. Then shifting back again once the sketch mode is completed. Obviously most of the typical tools wouldn't be active in the sketch mode & vice versa.

Additionally, possibility of collapsing/hiding the Sketch tool set once the sketch mode has been existed.

**Comment by hlorus** [comment]
That would be a nice addition indeed
