### ISSUE TITLE
Linked Arcs: Redundant Contraints or Inconsistent

### ISSUE THREAD

**Issue by jaherbert1** [hlorus/CAD_Sketcher#392]
### Contact Details

jaherbert@hotmail.com

### Description

Linking arcs across sketches in the same workplane yields either Redundant Constraints or Inconsistent.

Steps:

Create Sketch1 on a workplane and draw an arc.  Make sure Sketch1 is visible.

Create Sketch2 on same workplane.

Draw an arc on Sketch2 that's not coincident with any of the points on Sketch1.  Now make the three points on Sketch2 coincident with the corresponding points on Sketch1.

Alternatively, construct the arc on Sketch2 making one or more of the points coincident with the corresponding points during the construction.  Now make coincident any remaining points.

In both cases, you should get one of the errors cited above.

If you do the same procedure with a line segment, you get the expected, error-free result.

### Addon Version

0.27.1

### Blender Version

3.5.1

### What platform are you running on?

Windows

**Comment by hlorus** [comment]
If i understand it correctly this is expected behavior. Reference geometry is interpreted as "fixed" and the radius of the arc is over constrained if all points are fixed. Try to fix only two points and define the angle of the arc.
