### ISSUE TITLE
[BUG] Distance constraint 'only measure' alignment non functional

### ISSUE THREAD

**Issue by kayboy-bebop** [hlorus/CAD_Sketcher#394]
### Description

When using the distance constraint to measure the distance between 2 points or a line, the alignment option doesn't change the measured distance. The graphic does align to vertical/horizontal.
![bug](https://github.com/hlorus/CAD_Sketcher/assets/115389530/8e14286d-4681-4b7b-908d-06a52d7900f9)

### Addon Version

0.27.1

### Blender Version

3.4.1

### What platform are you running on?

Windows

**Comment by artemoz** [comment]
Does reproduce on my end. Blender 3.5.0, CAD Sketcher 0.27.2 (`0963cc4`, downloaded yesterday), Windows.
Does affect horizontal/vertical distance. When changing the constraint to/from "Only measure" the value is set to total/diagonal distance instead.

Steps i've used:
1. Place a point to the top right of an origin
2. Select newly added point and origin, add Horizontal Distance constraint with Alt+H
3. Click on constraint, set "Only measure" in its context menu. Repeat multiple times.
Result:
Value is set to diagonal distance, gizmos miss the points, non-origin point gets moved when the constraint isn't "Only measure".
