### ISSUE TITLE
[BUG]Sketcher generated unexpected mesh

### ISSUE THREAD

**Issue by asp100m** [hlorus/CAD_Sketcher#399]
### Description

The following picture is design and result mesh.
![cad_test02_issue](https://github.com/hlorus/CAD_Sketcher/assets/61493234/f17d2096-20ef-4287-a488-a38cf986ad28)

Attached blend file:
[cad_test02.zip](https://github.com/hlorus/CAD_Sketcher/files/11958697/cad_test02.zip)

### Addon Version

0.27.2

### Blender Version

3.6

### What platform are you running on?

Windows

**Comment by hlorus** [comment]
This isn't considered a bug, you'll need to clean up your geometry, check the limitations and best practices here: https://hlorus.github.io/CAD_Sketcher/integration/
