### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by bguenthe** [hlorus/CAD_Sketcher#402]
### Contact Details

bernd.stuebe@gmail.com

### Description

I tried your plugin on a Macbook Pro (M1) chip. When I click the "new sketch" button I can't see any plane in the 3D viewport.

### Addon Version

latest

### Blender Version

3.6

### What platform are you running on?

Mac OSX

**Comment by hlorus** [comment]
That's a known issue, see the warning in the readme:
Mac OS: Due to an ongoing Blender bug apple Metal users need to change their GPU Backend to OpenGL under: edit->preferences->system->GPU Backend


Closing as duplicate of #375
