### ISSUE TITLE
[BUG] Extra lines on my mesh

### ISSUE THREAD

**Issue by ClayShoaf** [hlorus/CAD_Sketcher#405]
### Description

For some reason (maybe I have too many constraints, maybe I don't have enough) sometimes when I am exiting a sketch, there will be and extra line (plane? Sorry, I don't know all of the terminology) as you can see in the image on the left side of the "M". 
![image](https://github.com/hlorus/CAD_Sketcher/assets/31578812/ae11037a-611c-41fa-bc8e-cd6f61aa9f4b)

This is causing problems when I try to do a bool operation.

If I solidify it, it creates all kinds of crazy faces that you can see in wireframe view:
![image](https://github.com/hlorus/CAD_Sketcher/assets/31578812/18578c7a-9a4e-4f36-82d4-6741fe7e1e57)

The only way I can make it go away is if I delete the horizontal constraint on that line of the "M" and then move the line a little bit so that it isn't perfectly horizontal, but this is obviously not a solution.
![image](https://github.com/hlorus/CAD_Sketcher/assets/31578812/d1048352-c56c-4309-bee2-8943deace1f0)

I'm just wondering if this is a bug, or if I'm doing something wrong.

### Addon Version

0.27.2

### Blender Version

3.6.0

### What platform are you running on?

Linux

**Comment by hlorus** [comment]
This comes from the fact that blender is mesh-based. The addon converts the geometry to blenders bezier curves, the extra lines then come from blenders bezier-mesh converter. You should be able to remove them with a decimate modifier.

**Comment by ClayShoaf** [comment]
But then why does it not happen if I remove the constraint and move the point a little bit?
