### ISSUE TITLE
Minor issue: using CAD sketcher always switches to teak tool

### ISSUE THREAD

**Issue by zevv** [hlorus/CAD_Sketcher#418]
### Description

This is a minor UX issue, but it would be nice if this behavior can be changed:

The default blender tool is the "select box", but when entering and leaving a sketch, the tool always switches to tweak mode instead. Would it be possible to restore the original mode when leaving the sketch?

Reproduction:

- activate "select box" tool
- edit a sketch
- leave sketch
- observe tool is now switched to "tweak"

### Addon Version

latest

### Blender Version

latest

### What platform are you running on?

Linux

**Comment by hlorus** [comment]
Thanks for reporting, this should be resolved with 587bded196dcf1c9d01f1b5fc8b0f909b27b3915
