### ISSUE TITLE
CAD Sketcher 0.27.2 on Mac M1 [BUG]

### ISSUE THREAD

**Issue by stesj4** [hlorus/CAD_Sketcher#423]
### Contact Details

stefan.ake.sjoberg@gmail.com

### Description

Can't choose a plane to start with. Can't open old sketches made in Blender 3.x.

### Addon Version

0.27.2

### Blender Version

4.0.0

### What platform are you running on?

Mac OSX

**Comment by avpayne** [comment]
Same issue.  Running on a Mac M1 powerbook, macOS Monterey, Blender 4.0.0, CAD Sketcher 0.27.2.  Have tried many combinations for configuring Preferences|System|Cycles Render Devices (in case it's GPU related), but no settings seem to fix this issue.

**Comment by hlorus** [comment]
Should be fixed now, see: #424
