### ISSUE TITLE
Text not visible

### ISSUE THREAD

**Issue by CJagd** [hlorus/CAD_Sketcher#428]
Hi

I'm unable to get the text showing 
EG: I have a diameter contraint, but it dimention is not showing up.
<img width="532" alt="image" src="https://github.com/hlorus/CAD_Sketcher/assets/48928180/b3926707-79ac-4ef0-8e5b-3ddf9e91be08">

Any Idea ?

**Comment by RichH53** [comment]
It does the same for me in Blender 4. Blender 3.62 worked fine with the same file and CAD Sketcher version. The console shows the following error:
.py", line 205, in draw
    blf.size(FONT_ID, text_size, dpi)
TypeError: blf.size() takes exactly 2 arguments (3 given)

**Comment by RichH53** [comment]
Thank you. That fixed it.
