### ISSUE TITLE
[BUG] Entity scale changes only points, not lines

### ISSUE THREAD

**Issue by kushney** [hlorus/CAD_Sketcher#432]
### Contact Details

vladyslav.kushney@gmail.com

### Description

A bug happened!

Seems to be same issue as [this](https://github.com/users/hlorus/projects/1/views/1?pane=issue&itemId=4293216)

Blender and cad sketcher freshly installed. 

I use M1 Mac Mini, Mac OS Sonoma 14.0, 4k displays.

<img width="2560" alt="Screenshot 2023-12-10 at 13 56 23" src="https://github.com/hlorus/CAD_Sketcher/assets/10085582/0d8acfe5-9a95-48de-ab11-74f7de10ed34">

<img width="2560" alt="Screenshot 2023-12-10 at 13 56 10" src="https://github.com/hlorus/CAD_Sketcher/assets/10085582/219d52f4-41fb-47b2-a116-ec19bfda7ba6">

### Addon Version

0.27.3

### Blender Version

4.0.2

### What platform are you running on?

Mac OSX

**Comment by hlorus** [comment]
This is a known limitation on mac. This won't be fixed on the addon side but might be addressed by blender itself at some point.
