### ISSUE TITLE
Cad Sketcher Solver module isn't registered

### ISSUE THREAD

**Issue by Ekouas** [hlorus/CAD_Sketcher#445]
### Contact Details

evykouassi@hotmail.com

### Description

A bug happened! The solver module isn't registered while installing the Cad sketcher Add-on on the blender App.
We can't also install it "from file"
The OS is Win 10.
Thank you for your answer.

### Addon Version

V0.27

### Blender Version

v3.6.4 

### What platform are you running on?

Windows

**Comment by hlorus** [comment]
Thanks for the report. With blender 4.20 CAD Sketcher is installed as an extension which brings support for pip dependencies. Blender will install the correct solver module when the extension is installed.
