### ISSUE TITLE
[BUG] "RuntimeError: Operator bpy.ops.ed.undo.poll() failed, context is incorrect" in Blender 4.0.2 on Mac

### ISSUE THREAD

**Issue by axel-tanner** [hlorus/CAD_Sketcher#448]
### Contact Details

axel.tanner@posteo.ch

### Description

- using Blender 4.0.2 
- on MacOS 14.2.1 
- on a MacBook M1 Pro

after installation of CAD Sketcher 0.27.3 add-on and installation of the solver module (and restart of Blender), I can create a sketch, select a workplane - but whatever I try like adding a point, a rectangle etc, I get an error popup. 
Error on the console is like

`Error: Python: Traceback (most recent call last):
  File "/Users/abc/Library/Application Support/Blender/4.0/scripts/addons/CAD_Sketcher-main/stateful_operator/logic.py", line 512, in modal
    return self.evaluate_state(context, event, event_triggered)
  File "/Users/abc/Library/Application Support/Blender/4.0/scripts/addons/CAD_Sketcher-main/stateful_operator/logic.py", line 580, in evaluate_state
    bpy.ops.ed.undo()
  File "/Applications/Blender.app/Contents/Resources/4.0/scripts/modules/bpy/ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
RuntimeError: Operator bpy.ops.ed.undo.poll() failed, context is incorrect`

Any idea what could be the problem?
Thanks!

### Addon Version

0.27.3

### Blender Version

4.0.2

### What platform are you running on?

Mac OSX

**Comment by xabbu137** [comment]
For whatever reason, after a (another) reinstall of CAD Sketcher (same version, also same version of Blender) it works now. Don't know what was different this time, but it seems fixed.
