### ISSUE TITLE
[BUG] FreeBSD platform is not supported during install

### ISSUE THREAD

**Issue by vslash** [hlorus/CAD_Sketcher#464]
### Contact Details

valery@vslash.com

### Description

We cannot install the addon due to no support in bae/preferences.py for FreeBSD OS:
`  
File "/home/valery/.config/blender/3.6/scripts/addons/CAD_Sketcher-main/base/preferences.py", line 71, in get_wheel
    version_info.major, version_info.minor, platform_strig
UnboundLocalError: local variable 'platform_strig' referenced before assignment
`

Expected value:
```
import sys
sys.platform
'freebsd14'
```

bugfix could be like:

```
def get_wheel():
    p = Path(__file__).parent.absolute()
    from sys import platform, version_info

    if platform == "linux" or platform == "linux2":
        # Linux
        platform_strig = "linux"
    elif platform == "darwin":
        # OS X
        platform_strig = "macosx"
    elif platform == "win32":
        # Windows
        platform_strig = "win"
    elif platform.startswith("freebsd")
        # FreeBSD
        platform_strig = "freebsd"

```
but I don't know the future use for `platform_strig`, so `"linux"` could be a better value.

### Addon Version

0.27

### Blender Version

3.6

### What platform are you running on?

Linux

**Comment by hlorus** [comment]
Thanks for the report. With blender 4.20 CAD Sketcher is installed as an extension which brings support for pip dependencies. Blender will install the correct solver module when the extension is installed.
