### ISSUE TITLE
[BUG] Pip tries to install solver module globally

### ISSUE THREAD

**Issue by andrewbaxter** [hlorus/CAD_Sketcher#468]
### Contact Details

here

### Description

I'm not sure what exact command CAD Sketcher runs for pip, but I assume it does it outside of a virtual environment.  On Arch this is now restricted per https://peps.python.org/pep-0668/ with this warning message:
```
pip 24.0 from /usr/lib/python3.12/site-packages/pip (python 3.12)
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try 'pacman -S
    python-xyz', where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Arch-packaged Python package,
    create a virtual environment using 'python -m venv path/to/venv'.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip.
    
    If you wish to install a non-Arch packaged Python application,
    it may be easiest to use 'pipx install xyz', which will manage a
    virtual environment for you. Make sure you have python-pipx
    installed via pacman.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```

I'm not sure this is solvable.  If blender runs in the system python context, solving it may require the user to run blender itself in a virtual environment to package, if that works at all (I haven't tried it, and it sounds hacky). https://projects.blender.org/blender/blender/issues/71420 describes a lot of issues with how blender handles pypi, including venvs, but it doesn't look like it's gone anywhere... I assume Windows is okay because the python bundled with blender is effectively a limited environment.

I assume the reason the solver can't be packaged together is because it's a c extension and needs to be compiled for each user?

### Addon Version

0.27.3

### Blender Version

4.1.1

### What platform are you running on?

Linux

**Comment by hlorus** [comment]
Thanks for the report. With blender 4.20 CAD Sketcher is installed as an extension which brings support for pip dependencies. Blender will install the correct solver module when the extension is installed.
