### ISSUE TITLE
Constraints selectability

### ISSUE THREAD

**Issue by hlorus** [hlorus/CAD_Sketcher#48]

**Comment by exegetor** [comment]
can you elaborate on this?   what it would look like and what effects would be possible?

**Comment by hlorus** [comment]
@TheMakerTales might know better but as far as i understand it the task is ment to solve the problem of gizmos that obscure entities and therefore disallow entity selection.

IIRC @TheMakerTales proposed to have a toggle which disables gizmos selectability but still renders them.

I'm not sure if this is really needed when we have the constraints visibility toggle as described in #47.

**Comment by TheMakerTales** [comment]
@exegetor what hlorus says is correct. It's a way of still seeing the gizmos but making them not selectable as they can sometimes get in the way of more complicated sketches.
