### ISSUE TITLE
[BUG] Unable to install 0.27.6

### ISSUE THREAD

**Issue by raindropsfromsky** [hlorus/CAD_Sketcher#498]
### Contact Details

raindrops.fromsky@gmail.com

### Description

 I am unable to install the latest version of CAD Sketcher (0.27.6).

- I tried to drag-and-drop the zip on Blender UI.
- I tried installing from disk.

In both, the console shows the following errors: 

2024-12-25 13:25:37,020     INFO logging.py 25 Logging into: 
C:\Users\<UserName>\AppData\Local\Temp\bl_ext.user_default.CAD_Sketcher-naray.log

Error: Unable to retrieve addon version

### Addon Version

0.27.6

### Blender Version

Bforartyists 4.4.0 Alpha

### What platform are you running on?

Windows

**Comment by hlorus** [comment]
I've pushed a commit to get rid of the toml dependency, please get the newest version from github.
