### ISSUE TITLE
Add drag box selection

### ISSUE THREAD

**Issue by hlorus** [hlorus/CAD_Sketcher#57]

**Comment by Shaddy-ElDesouky** [comment]
maybe lasso selection too will be good

**Comment by ftc** [comment]
It may be nice to make this consistent with the "edit" mode selection of Blender.  Specifically the [box and circle select](https://docs.blender.org/manual/en/2.80/modeling/meshes/selecting.html).  I always find that I miss the circle select feature when using other cad programs.
