### ISSUE TITLE
Entity conversion resolution 

### ISSUE THREAD

**Issue by hlorus** [hlorus/CAD_Sketcher#58]
Right now converted meshes approximate curves with a given resolution. Ideally this resolution could be configured as users might want more detail on the converted mesh.

Since mesh converting is currently based on the bezier converter this simply boils down to setting the correct values in the bezier datablock before the to_mesh()  method is called. Note that setting this property by the user doesn't work because the bezier object is temporary an gets recreated every time conversion happens.

This setting could probably be put in one of a few different scopes e.g. one setting for the addon/ per sketch/ per spline. For now it should be sufficient to simply have it per sketch.

**Comment by SupinePandora43** [comment]
What about `multires` support too?

**Comment by Cheaterman** [comment]
Hello! Sorry if this should be obvious, but I don't really understand what this feature is about ; could it be possible to add some additional information, given this is tagged as "good first issue"? I'm thinking "current behavior", "expected behavior", and some pointers as to where in the codebase the change should be made?

It would be awesome if such extra information could be added to other issues with the "good first issue" tag too, please :-) thanks in advance!

**Comment by SupinePandora43** [comment]
> Hello! Sorry if this should be obvious, but I don't really understand what this feature is about ; could it be possible to add some additional information, given this is tagged as "good first issue"? I'm thinking "current behavior", "expected behavior", and some pointers as to where in the codebase the change should be made?
> 
> It would be awesome if such extra information could be added to other issues with the "good first issue" tag too, please :-) thanks in advance!

There's no way to specify how many polygons sketch-to-mesh result should have (i think)

**Comment by hlorus** [comment]
> Hello! Sorry if this should be obvious, but I don't really understand what this feature is about ; could it be possible to add some additional information, given this is tagged as "good first issue"? I'm thinking "current behavior", "expected behavior", and some pointers as to where in the codebase the change should be made?
> 
> It would be awesome if such extra information could be added to other issues with the "good first issue" tag too, please :-) thanks in advance!

Absolutely agree with that, thanks for pointing out! :)

**Comment by hlorus** [comment]
IMO it's better to have this solved by a generic system rather than hardcoding properties that the user might want to change.

There is already an attempt to solve this, see #200.

**Comment by hlorus** [comment]
Closed by fd3b9e3cc30dbbac5a27f3ed840ff1487b40621c
