### ISSUE TITLE
[BUG]  Hi.  I just purchased CAD Sketcher with $20 donation and did everything I am supposed to do by installing the add on and activate solver. But when I activate sketcher by sowing side menu and press add sketch, yes the XYZ surface place appears on 3D view port ... but that it. These XYZ planes somehow flickers like a weak flush and I can never select the plane. There appears Python error message and I cannot do anything except I go away form the sketcher.  

### ISSUE THREAD

**Issue by SoraSpace** [hlorus/CAD_Sketcher#62]
**Description**

**To Reproduce**
1. 
2. 

**Expected behavior**

**Screenshots**

**System Information:**
 - OS:  
 - Blender Version: 
 - Addon Version:

Hi. I just purchased CAD Sketcher with $20 donation and did everything I am supposed to do by installing the add on and activate solver. But when I activate sketcher by sowing side menu and press add sketch, yes the XYZ surface place appears on 3D view port ... but that it. These XYZ planes somehow flickers like a weak flush and I can never select the plane. There appears Python error message and I cannot do anything except I go away form the sketcher.

**Comment by TheMakerTales** [comment]
Hi SoraSpace, I would recommend heading over to the [discord](https://discord.gg/GzpJsShgxa) and asking in the [ installation-help ] channel along with the other help channel if you think it's not installation related.
