### ISSUE TITLE
[REQUEST]when selecting a plane to do a sketch on it, it can only be selected by clicking on the exterior lines, and i can't find where to change its width so.. the line is soooo thin that i can't put the cursor over it to select the plane. it would be great to select on the plane itself or the lines must be much bigger. thanks.

### ISSUE THREAD

**Issue by capisweb** [hlorus/CAD_Sketcher#63]
**Motivation / Existing Problem**

**Description**

**Alternative Solutions**

**Mockup**
Ideally add a quick drawing to show how this would look.

**Comment by TheMakerTales** [comment]
Hi SoraSpace, I would recommend heading over to the [discord](https://discord.gg/GzpJsShgxa) and asking in the help channel before adding feature requests. The feature to increase the line width is already implemented under the addon setting showcased in this video: [Youtube Video](https://youtu.be/92QmjS-xDaI?t=126 )
It's an interesting suggestion to add the availability to select via the planes themselves and not the outside end so I'll add this over into the feature requests in [discussions](https://github.com/hlorus/CAD_Sketcher/discussions)
