### ISSUE TITLE
Solver Module not option to select

### ISSUE THREAD

**Issue by SCON1233** [hlorus/CAD_Sketcher#80]
### Contact Details

sheri@omahaneon.com

### Description

Trying to install CAD-Sketcher into Blender 3.1.2
Instructions state to select "Solver Module" However there is a message stating "Module isnt registered"
Is this a bug, or am i missing something?

Any Help Greatly appreciated.

### Addon Version

0.21.0

### Blender Version

3.1.2

**Comment by TheMakerTales** [comment]
Hi SCON1233, Thank you for getting in conntact. I would recommend heading over to the [discord](https://discord.gg/GzpJsShgxa) and asking in the [ installation-help ] channel.
