### ISSUE TITLE
'Only' sketching?

### ISSUE THREAD

**Issue by Jopie01** [hlorus/CAD_Sketcher#81]
First, Many thanks for this addon. I was just wondering, is this addon only meant to do sketching? Or also do the more generic CAD actions like extrude, revolve, rounds and chamfers?

**Comment by TheMakerTales** [comment]
Hi Jopie thank you for getting in contact but please don't use issues tickets for general discussion. We would love it if you would head over to the [discord](https://discord.gg/GzpJsShgxa) and the community along with dev's as a whole will be more than happy to reply there.
