### ISSUE TITLE
[BUG] workplanes do not show up (2.93.6)

### ISSUE THREAD

**Issue by RogueSheep-nl** [hlorus/CAD_Sketcher#83]
### Description

When clicking 'Add Sketch' the cursor shapes changes to a crosshair but the workplanes are not visible in the 3D viewport.
The status bar states: '_Workplane: Pick a workplane as base for the sketch. Types: [SlvsWorkplane]_'

### Addon Version

0.21.0

### Blender Version

2.93.6

### What platform are you running on?

Windows

**Comment by hlorus** [comment]
Thanks for reporting, this will be resolved in the next update.
