### ISSUE TITLE
Sketch Planes too small

### ISSUE THREAD

**Issue by subsam69** [hlorus/CAD_Sketcher#86]
I have set up Blender for 3D Printier modeling so scaled to 0.001 so when starting new sketch the planes are too small to see and select.

**Comment by TheMakerTales** [comment]
I agree with you on this one. Take a look at the discussions there is a feature request along these lines: [Workplane Size Control ](https://github.com/hlorus/CAD_Sketcher/discussions/76)
Maybe add a few more comments on how it would help your workflow and upvote it
