### ISSUE TITLE
[REQUEST] Change how diamater constriant is displayed

### ISSUE THREAD

**Issue by Maykeye** [hlorus/CAD_Sketcher#89]
**Motivation / Existing Problem**

Now diameter constraint has text inside the circle:
![image](https://user-images.githubusercontent.com/13607441/166144086-84c38333-9ad1-4216-b4a6-f02283e582e5.png)

Constraint line and text completely cover the center point. I can't do anything with it.
If I try to draw a new line from the center point, I can't, at least every time I try, it prompts to change/delete constraint, even though I use tool to draw 2d line, not selection tool:
![image](https://user-images.githubusercontent.com/13607441/166144331-1b429d3b-785c-4dde-886a-10a0b082b2b3.png)

**Description what should happen**
I should be able to choose center point without pixel hunting for it. Right now we can move distance constraint around. We can only rotate diameter constraint around the center, but it rotates constraint line without moving the text.

**Alternative Solutions**
1) I find it's easier to not use diameter constraint at all and instead create vertical/horizontal line and add distance constraint=radius of circle
![image](https://user-images.githubusercontent.com/13607441/166144552-4fd058df-ca36-45b1-bd5e-9d48ac383c68.png)

2) I can try to start line from another point and land near center, hoping that the center will be selected, but most of the times I create new point instead, but it wouldn't work if I want to draw a line between two circles with constrained diameter

**Mockup**
* Add ability to move text out of the circle, so center point can be selected, like this
![image](https://user-images.githubusercontent.com/13607441/166145095-aa92d709-5a81-497e-8f03-01ad00b14091.png)

* If user clicks near center point, blender should prioritize selecting center point, not constraint.

**Comment by TheMakerTales** [comment]
Hi Maykeye,
Thanks for the detailed request. I'm happy to say that something like this is already planned: [https://github.com/hlorus/CAD_Sketcher/issues/60](https://github.com/hlorus/CAD_Sketcher/issues/60)

**Comment by deathbypain** [comment]
To add on to this, if two circles that share a center point both have diameter constraints, the text for the constraint display overlaps and is illegible.

![overlapping_center_constraints](https://user-images.githubusercontent.com/74065088/167539012-754c5512-6566-426d-b273-3ad6cc4f4278.jpg)
