### ISSUE TITLE
Dimensions

### ISSUE THREAD

**Issue by hrjrkr** [hlorus/CAD_Sketcher#90]
### Contact Details

joerocha1982@outlook.com

### Description

I had a dimension on a line. When I went to move one of the corners over, the dimension did not follow.
Thanks
Joe

### Addon Version

0.21.0

### Blender Version

3.1.2

### What platform are you running on?

Windows

**Comment by TheMakerTales** [comment]
Hi hrjrkr,
Thanks for writing in. I have a feeling this would be best suited to bring up in the [discord ](https://discord.gg/GzpJsShgxa) server under help as I have a feeling this might be due to over constraining a sketch.
