### ISSUE TITLE
Keeping Material & Shading properties after Sketch edits

### ISSUE THREAD

**Issue by TheMakerTales** [hlorus/CAD_Sketcher#93]

**Comment by hlorus** [comment]
I've made a change to not always create a new mesh data block, this should help for properties that are stored on the mesh. However it's another story for data that is stored on mesh elements as they get overwritten. This is somewhat related to #6 as existing data would then only be updated...

**Comment by TheMakerTales** [comment]
shading might not be supported but wow, materials sorted plus that also added support for linked duplicates

**Comment by TheMakerTales** [comment]
Shall this issue now be closed and a feature request for smooth shading support?

**Comment by hlorus** [comment]
> Shall this issue now be closed and a feature request for smooth shading support?

Yeah i'd say that makes sense.

**Comment by TheMakerTales** [comment]
Smooth Shading Support moved to feature requests https://github.com/hlorus/CAD_Sketcher/discussions/104
