### ISSUE TITLE
Cannot apply modifiers [BUG]

### ISSUE THREAD

**Issue by jmaitlandsoto** [hlorus/CAD_Sketcher#94]
### Contact Details

maitland.joshua@gmail.com

### Description

I am using CAD Sketcher to create a drawer organizer, which I plan to 3D print. I am using the  Boolean (difference) modifier to hollow out the object, as well as others, like solidify, and bevel. Before exporting to STL I have to apply all the modifiers. When I try to apply a modifier the apply option is greyed out and it says "Disabled: Modifiers cannot be applied to multi-user data".
![Capture](https://user-images.githubusercontent.com/76271602/166175033-08d1c4c3-fd5a-462c-8691-cad6d3533586.PNG)

### Addon Version

0.21.0

### Blender Version

3.0.0

### What platform are you running on?

Windows

**Comment by hlorus** [comment]
Hmm not quite sure about this, what would you expect after you've applied modifiers? This would obviously break the whole non-destructive workflow. Once you'd update the sketch the mesh would get overwritten...

So one solution would be to have an bake operation which applys modifiers and delets the sketch.

That being said, did you try one of the newer blender versions? I remember there were some improvements to how multi-user data is handled. Ideally exporters could temporary bake the data they need but not sure if that was addressed...

**Comment by TheMakerTales** [comment]
This has now been solved in version 0.22.2 [https://makertales.gumroad.com/l/CADsketcher](gumroad to latest "satble" version)
